# ============================================================
# Auto-generated openEMS simulation script
# Generated by AntennaSimulatorApp
# ============================================================

import os, sys
import numpy as np

post_only = '--post-only' in sys.argv

# --- Locate openEMS ---
script_dir = os.path.dirname(os.path.abspath(__file__))
sim_base = os.path.dirname(script_dir)  # Sim/
geometry_dir = os.path.join(sim_base, 'geometry')
sim_data_dir = os.path.join(sim_base, 'sim_data')
results_dir  = os.path.join(sim_base, 'results')

openems_path = r'C:\Users\Bin Xiao\OneDrive\Desktop\PCBAntSim\openEMS'
if openems_path and os.path.isdir(openems_path):
    os.add_dll_directory(openems_path)
    print(f'openEMS found: {openems_path}')
else:
    print('WARNING: openEMS folder not found, relying on system PATH')

from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import *

# --- Simulation Parameters ---
unit = 1e-3  # all coordinates in mm
f_start = 1000000000
f_stop  = 4000000000
f0      = 2500000000

# --- FDTD Setup ---
sim = openEMS(NrTS=200000, EndCriteria=1E-05)
sim.SetGaussExcite(f0, (f_stop - f_start) / 2)
sim.SetBoundaryCond(['PML_4', 'PML_4', 'PML_4', 'PML_4', 'PML_4', 'PML_4'])

csx = ContinuousStructure()
mesh = csx.GetGrid()
mesh.SetDeltaUnit(unit)

# --- Materials ---
copper = csx.AddMetal('Copper')
mat_fr4 = csx.AddMaterial('mat_fr4', epsilon=4.3, kappa=0.02)

# --- Carrier Board Geometry ---
mat_fr4.AddBox([-40, -100, -0.2], [40, 0, 0], priority=0)
mat_fr4.AddBox([-40, -100, -1.46], [40, 0, -0.2], priority=0)

# carrier_CARRIER_L2_GND_main_0
copper.AddPolygon(np.array([[-40, -40, 40, 40, 15, 15, -15, -15], [0, -100, -100, 0, 0, -4, -4, 0]]), 'z', -0.2, priority=12)
# carrier_CARRIER_TOP_GND_main_1
copper.AddPolygon(np.array([[-40, -40, 40, 40, 15, 15, -15, -15], [0, -100, -100, 0, 0, -4, -4, 0]]), 'z', 0, priority=12)
# --- RF Module Geometry ---
mat_fr4.AddBox([-5.1, -15, 0.1], [5.1, -0, 0.39], priority=0)
mat_fr4.AddBox([-5.1, -15, 0.39], [5.1, -0, 0.49], priority=0)

# module_MODULE_L3_GND_main_0
copper.AddPolygon(np.array([[-5.1, -5.1, 5.1, 5.1], [-4, -15, -15, -4]]), 'z', 0.39, priority=12)
# module_MODULE_TOP_GND_main_1
copper.AddPolygon(np.array([[-3.3, 5.1, 5.1, -2.4, -2.4, -3.1, -3.1, -3.3, -3.3, -5.1, -5.1], [-7, -7, -4.4, -4.4, -4.7, -4.7, -4.4, -4.4, -4, -4, -7]]), 'z', 0.49, priority=12)
# module_MIFA_COPPER_main_2
copper.AddPolygon(np.array([[4.1, 4.4, 4.4, 4.1], [-3.2, -3.2, -3.7, -3.7]]), 'z', 0.49, priority=12)
# module_MODULE_BOT_main_3
copper.AddPolygon(np.array([[-5.1, -5.1, 5.1, 5.1], [-4, -15, -15, -4]]), 'z', 0.1, priority=12)
# module_Antenna (MIFA)_main_4
copper.AddPolygon(np.array([[-4.6, -3.3, -3.3, -4.6], [-4.3, -4.3, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_0
copper.AddPolygon(np.array([[-4.6, -2.6, -2.6, -4.6], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_1
copper.AddPolygon(np.array([[-2.9, -2.6, -2.6, -2.9], [-4.3, -4.3, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_2
copper.AddPolygon(np.array([[-2.9, -1.6, -1.6, -2.9], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_3
copper.AddPolygon(np.array([[-1.9, -1.6, -1.6, -1.9], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_4
copper.AddPolygon(np.array([[-1.9, -0.6, -0.6, -1.9], [-3.55, -3.55, -3.25, -3.25]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_5
copper.AddPolygon(np.array([[-0.9, -0.6, -0.6, -0.9], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_6
copper.AddPolygon(np.array([[-0.9, 0.4, 0.4, -0.9], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_7
copper.AddPolygon(np.array([[0.1, 0.4, 0.4, 0.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_8
copper.AddPolygon(np.array([[0.1, 1.4, 1.4, 0.1], [-3.55, -3.55, -3.25, -3.25]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_9
copper.AddPolygon(np.array([[1.1, 1.4, 1.4, 1.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_10
copper.AddPolygon(np.array([[1.1, 2.4, 2.4, 1.1], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_11
copper.AddPolygon(np.array([[2.1, 2.4, 2.4, 2.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_12
copper.AddPolygon(np.array([[2.1, 3.4, 3.4, 2.1], [-3.55, -3.55, -3.25, -3.25]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_13
copper.AddPolygon(np.array([[3.1, 3.4, 3.4, 3.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_14
copper.AddPolygon(np.array([[3.1, 4.4, 4.4, 3.1], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0.49, priority=15)
# module_Antenna (MIFA)_merged_4_15
copper.AddPolygon(np.array([[4.1, 4.4, 4.4, 4.1], [-3.3, -3.3, -0.1, -0.1]]), 'z', 0.49, priority=15)
# --- Vias ---
copper.AddCylinder([-3.6, -4.6, 0.1], [-3.6, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([-4.8, -4.6, 0.1], [-4.8, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([-4.2, -4.6, 0.1], [-4.2, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([-2, -4.6, 0.1], [-2, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([-1, -4.6, 0.1], [-1, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([0, -4.6, 0.1], [0, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([1, -4.6, 0.1], [1, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([2, -4.6, 0.1], [2, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([3, -4.6, 0.1], [3, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([4, -4.6, 0.1], [4, -4.6, 0.49], 0.1524, priority=15)
copper.AddCylinder([0, -4.6, -1.46], [0, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([1, -4.6, -1.46], [1, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([2, -4.6, -1.46], [2, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([3, -4.6, -1.46], [3, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([4, -4.6, -1.46], [4, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([5, -4.6, -1.46], [5, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([6, -4.6, -1.46], [6, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([7, -4.6, -1.46], [7, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([8, -4.6, -1.46], [8, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([9, -4.6, -1.46], [9, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([10, -4.6, -1.46], [10, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-1, -4.6, -1.46], [-1, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-2, -4.6, -1.46], [-2, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-3, -4.6, -1.46], [-3, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-4, -4.6, -1.46], [-4, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-5, -4.6, -1.46], [-5, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-6, -4.6, -1.46], [-6, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-7, -4.6, -1.46], [-7, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-8, -4.6, -1.46], [-8, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-9, -4.6, -1.46], [-9, -4.6, 0], 0.254, priority=15)
copper.AddCylinder([-10, -4.6, -1.46], [-10, -4.6, 0], 0.254, priority=15)

# --- Solder Joints (module bottom → carrier top) ---
copper.AddCylinder([0, -4.6, 0], [0, -4.6, 0.1], 0.381, priority=15)
copper.AddCylinder([2, -4.6, 0], [2, -4.6, 0.1], 0.381, priority=15)
copper.AddCylinder([4, -4.6, 0], [4, -4.6, 0.1], 0.381, priority=15)
copper.AddCylinder([-2, -4.6, 0], [-2, -4.6, 0.1], 0.381, priority=15)
copper.AddCylinder([-4, -4.6, 0], [-4, -4.6, 0.1], 0.381, priority=15)

# --- Ports ---
from openEMS.ports import LumpedPort
ports = []
ports.append(LumpedPort(csx, 1, 50, [-2.9, -4.3, 0.39], [-2.6, -4, 0.49], 2, 1.0, priority=50))

# --- Mesh ---
mesh.AddLine('x', [-50, -40, 40, 50])
mesh.AddLine('y', [-110, -100, 0, 10])
mesh.AddLine('z', [-11.46, -1.46, -0.2, 0, 0.1, 0.39, 0.49, 10.49])
mesh.AddLine('x', [-5.1, 5.1])
mesh.AddLine('y', [-15, -0])
mesh.AddLine('x', [-2.9, -2.75, -2.6])
mesh.AddLine('y', [-4.3, -4.15, -4])
mesh.AddLine('x', [-3.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-1])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [0])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [1])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [0])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [1])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [5])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [7])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [9])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [10])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-1])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-5])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-7])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-9])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-10])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-40, -15, -14.67, -14.34, -14.01, -13.68, -13.35, -13.02, -12.69, -12.36, -12.03, -11.7, -11.37, -11.04, -10.71, -10.38, -10.05, -9.72, -9.39, -9.06, -8.73, -8.4, -8.07, -7.74, -7.41, -7.08, -6.75, -6.42, -6.09, -5.76, -5.43, -5.1, -4.933333, -4.766667, -4.6, -4.455556, -4.311111, -4.166667, -4.022222, -3.877778, -3.733333, -3.588889, -3.444444, -3.3, -3.2, -3.1, -3, -2.9, -2.8, -2.7, -2.6, -2.5, -2.4, -2.233333, -2.066667, -1.9, -1.8, -1.7, -1.6, -1.483333, -1.366667, -1.25, -1.133333, -1.016667, -0.9, -0.8, -0.7, -0.6, -0.483333, -0.366667, -0.25, -0.133333, -0.016667, 0.1, 0.2, 0.3, 0.4, 0.516667, 0.633333, 0.75, 0.866667, 0.983333, 1.1, 1.2, 1.3, 1.4, 1.516667, 1.633333, 1.75, 1.866667, 1.983333, 2.1, 2.2, 2.3, 2.4, 2.516667, 2.633333, 2.75, 2.866667, 2.983333, 3.1, 3.2, 3.3, 3.4, 3.516667, 3.633333, 3.75, 3.866667, 3.983333, 4.1, 4.2, 4.3, 4.4, 4.516667, 4.633333, 4.75, 4.866667, 4.983333, 5.1, 5.43, 5.76, 6.09, 6.42, 6.75, 7.08, 7.41, 7.74, 8.07, 8.4, 8.73, 9.06, 9.39, 9.72, 10.05, 10.38, 10.71, 11.04, 11.37, 11.7, 12.03, 12.36, 12.69, 13.02, 13.35, 13.68, 14.01, 14.34, 14.67, 15, 40])
mesh.AddLine('y', [-100, -15, -14.733333, -14.466667, -14.2, -13.933333, -13.666667, -13.4, -13.133333, -12.866667, -12.6, -12.333333, -12.066667, -11.8, -11.533333, -11.266667, -11, -10.733333, -10.466667, -10.2, -9.933333, -9.666667, -9.4, -9.133333, -8.866667, -8.6, -8.333333, -8.066667, -7.8, -7.533333, -7.266667, -7, -6.885, -6.77, -6.655, -6.54, -6.425, -6.31, -6.195, -6.08, -5.965, -5.85, -5.735, -5.62, -5.505, -5.39, -5.275, -5.16, -5.045, -4.93, -4.815, -4.7, -4.55, -4.4, -4.3, -4.15, -4, -3.85, -3.7, -3.55, -3.425, -3.3, -3.06, -2.92, -2.78, -2.64, -2.5, -2.36, -2.22, -2.08, -1.94, -1.8, -1.66, -1.52, -1.38, -1.24, -1.1, -0.96, -0.82, -0.68, -0.54, -0.4, -0.25, -0.1, 0])

mesh.SmoothMeshLines('x', 6.25, ratio=1.5)
mesh.SmoothMeshLines('y', 6.25, ratio=1.5)
mesh.SmoothMeshLines('z', 1, ratio=1.4)

# --- Run Simulation ---
sim_path = sim_data_dir
os.makedirs(sim_path, exist_ok=True)
csx.Write2XML(os.path.join(sim_path, 'antenna.xml'))
sim.SetCSX(csx)

if not post_only:
    print('Starting openEMS simulation...')
    sim.Run(sim_path, verbose=2, numThreads=8)
else:
    print('Post-processing only (--post-only mode)')

# --- Post-Processing: S11 ---
freq = np.linspace(1000000000, 4000000000, 501)
try:
    for p in ports:
        p.CalcPort(sim_path, freq)
except Exception as e:
    print(f'[WARN] Port data not ready yet: {e}')
    sys.exit(0)

if len(ports) == 0:
    print('[ERROR] No ports defined – cannot compute S11.')
    sys.exit(1)

s11_dB = 20 * np.log10(np.abs(ports[0].uf_ref / ports[0].uf_inc))
s11_complex = ports[0].uf_ref / ports[0].uf_inc
idx_min = np.argmin(s11_dB)
print(f'Resonance: {freq[idx_min]/1e9:.4f} GHz,  S11 = {s11_dB[idx_min]:.2f} dB')

# --- Save S11 CSV ---
csv_path = os.path.join(results_dir, 'S11.csv')
np.savetxt(csv_path, np.column_stack((freq / 1e9, s11_dB, np.real(s11_complex), np.imag(s11_complex))),
           delimiter=',', header='Frequency_GHz,S11_dB,S11_Real,S11_Imag', comments='')
print(f'S11 data saved to {csv_path}')

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.plot(freq / 1e9, s11_dB, 'b-', linewidth=1.5)
    ax.set_xlabel('Frequency (GHz)')
    ax.set_ylabel('S11 (dB)')
    ax.set_title('Return Loss')
    ax.grid(True)
    ax.axhline(-10, color='r', linestyle='--', alpha=0.5, label='-10 dB')
    ax.legend()
    plot_path = os.path.join(results_dir, 'S11.png')
    fig.savefig(plot_path, dpi=150)
    plt.close(fig)
    print(f'S11 plot saved to {plot_path}')
except ImportError:
    print('matplotlib not available - skipping plot.')

