# ============================================================
# Auto-generated openEMS simulation script
# Generated by AntennaSimulatorApp
# ============================================================

import os, sys
import numpy as np

post_only = '--post-only' in sys.argv

# --- Locate openEMS ---
script_dir = os.path.dirname(os.path.abspath(__file__))
sim_base = os.path.dirname(script_dir)  # Sim/
geometry_dir = os.path.join(sim_base, 'geometry')
sim_data_dir = os.path.join(sim_base, 'sim_data')
results_dir  = os.path.join(sim_base, 'results')

# Search upward for the openEMS folder
openems_path = None
_search = sim_base
for _ in range(5):
    _search = os.path.dirname(_search)
    _candidate = os.path.join(_search, 'openEMS', 'openEMS')
    if os.path.isdir(_candidate):
        openems_path = os.path.abspath(_candidate)
        break
if openems_path:
    os.add_dll_directory(openems_path)
    print(f'openEMS found: {openems_path}')
else:
    print('WARNING: openEMS folder not found, relying on system PATH')

from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import *

# --- Simulation Parameters ---
unit = 1e-3  # all coordinates in mm
f_start = 1000000000
f_stop  = 6000000000
f0      = 3500000000

# --- FDTD Setup ---
sim = openEMS(NrTS=200000, EndCriteria=1E-05)
sim.SetGaussExcite(f0, (f_stop - f_start) / 2)
sim.SetBoundaryCond(['PML_8', 'PML_8', 'PML_8', 'PML_8', 'PML_8', 'PML_8'])

csx = ContinuousStructure()
mesh = csx.GetGrid()
mesh.SetDeltaUnit(unit)

# --- Materials ---
copper = csx.AddMetal('Copper')
mat_fr4 = csx.AddMaterial('mat_fr4', epsilon=4.3, kappa=0.02)

# --- Carrier Board Geometry ---
mat_fr4.AddBox([-40, -100, -0.235], [40, 0, -0.035], priority=0)
mat_fr4.AddBox([-40, -100, -1.33], [40, 0, -0.27], priority=0)
mat_fr4.AddBox([-40, -100, -1.565], [40, 0, -1.365], priority=0)

# carrier_CARRIER_L2_GND_main_0
copper.AddLinPoly(np.array([[-40, -40, 40, 40, 15, 15, -15, -15], [0, -100, -100, 0, 0, -4, -4, 0]]), 'z', -0.27, 0.035, priority=12)
# carrier_CARRIER_TOP_GND_main_1
copper.AddLinPoly(np.array([[-40, -40, 40, 40, 15, 15, -15, -15], [0, -100, -100, 0, 0, -4, -4, 0]]), 'z', -0.035, 0.035, priority=12)
# --- RF Module Geometry ---
mat_fr4.AddBox([-5.1, -15, 0.135], [5.1, -0, 0.185], priority=0)
mat_fr4.AddBox([-5.1, -15, 0.22], [5.1, -0, 0.27], priority=0)
mat_fr4.AddBox([-5.1, -15, 0.305], [5.1, -0, 0.495], priority=0)
mat_fr4.AddBox([-5.1, -15, 0.53], [5.1, -0, 0.58], priority=0)
mat_fr4.AddBox([-5.1, -15, 0.615], [5.1, -0, 0.665], priority=0)

# module_MODULE_L3_GND_main_0
copper.AddLinPoly(np.array([[-5.1, -5.1, 5.1, 5.1], [-4, -15, -15, -4]]), 'z', 0.495, 0.035, priority=12)
# module_MODULE_TOP_GND_main_1
copper.AddLinPoly(np.array([[-3.3, 5.1, 5.1, -2.4, -2.4, -3.1, -3.1, -3.3, -3.3, -5.1, -5.1], [-7, -7, -4.4, -4.4, -4.7, -4.7, -4.4, -4.4, -4, -4, -7]]), 'z', 0.665, 0.035, priority=12)
# module_Antenna (MIFA)_main_2
copper.AddLinPoly(np.array([[-4.6, -3.3, -3.3, -4.6], [-4.3, -4.3, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_0
copper.AddLinPoly(np.array([[-4.6, -2.6, -2.6, -4.6], [-0.55, -0.55, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_1
copper.AddLinPoly(np.array([[-2.9, -2.6, -2.6, -2.9], [-4.3, -4.3, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_2
copper.AddLinPoly(np.array([[-2.9, -1.6, -1.6, -2.9], [-0.55, -0.55, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_3
copper.AddLinPoly(np.array([[-1.9, -1.6, -1.6, -1.9], [-3.4, -3.4, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_4
copper.AddLinPoly(np.array([[-1.9, -0.6, -0.6, -1.9], [-3.4, -3.4, -3.1, -3.1]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_5
copper.AddLinPoly(np.array([[-0.9, -0.6, -0.6, -0.9], [-3.4, -3.4, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_6
copper.AddLinPoly(np.array([[-0.9, 0.4, 0.4, -0.9], [-0.55, -0.55, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_7
copper.AddLinPoly(np.array([[0.1, 0.4, 0.4, 0.1], [-3.4, -3.4, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_8
copper.AddLinPoly(np.array([[0.1, 1.4, 1.4, 0.1], [-3.4, -3.4, -3.1, -3.1]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_9
copper.AddLinPoly(np.array([[1.1, 1.4, 1.4, 1.1], [-3.4, -3.4, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_10
copper.AddLinPoly(np.array([[1.1, 2.4, 2.4, 1.1], [-0.55, -0.55, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_11
copper.AddLinPoly(np.array([[2.1, 2.4, 2.4, 2.1], [-3.4, -3.4, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_12
copper.AddLinPoly(np.array([[2.1, 3.4, 3.4, 2.1], [-3.4, -3.4, -3.1, -3.1]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_13
copper.AddLinPoly(np.array([[3.1, 3.4, 3.4, 3.1], [-3.4, -3.4, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_14
copper.AddLinPoly(np.array([[3.1, 4.4, 4.4, 3.1], [-0.55, -0.55, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# module_Antenna (MIFA)_merged_2_15
copper.AddLinPoly(np.array([[4.1, 4.4, 4.4, 4.1], [-3.25, -3.25, -0.25, -0.25]]), 'z', 0.665, 0.035, priority=15)
# --- Vias ---
copper.AddCylinder([-3.6, -4.6, 0.1], [-3.6, -4.6, 0.7], 0.1524, priority=15)
copper.AddCylinder([-4.8, -4.6, 0.1], [-4.8, -4.6, 0.7], 0.1524, priority=15)
copper.AddCylinder([-4.2, -4.6, 0.1], [-4.2, -4.6, 0.7], 0.1524, priority=15)

# --- Ports ---
from openEMS.ports import LumpedPort
ports = []
ports.append(LumpedPort(csx, 1, 50, [-2.9, -4.3, 0.53], [-2.6, -4, 0.665], 2, 1.0, priority=50))

# --- Mesh ---
mesh.AddLine('x', [-50, -40, 40, 50])
mesh.AddLine('y', [-110, -100, 0, 10])
mesh.AddLine('z', [-11.6, -1.6, -1.565, -1.365, -1.33, -0.27, -0.235, -0.035, 0, 0.1, 0.135, 0.185, 0.22, 0.27, 0.305, 0.495, 0.53, 0.58, 0.615, 0.665, 0.7, 10.7])
mesh.AddLine('x', [-5.1, 5.1])
mesh.AddLine('y', [-15, -0])
mesh.AddLine('x', [-2.9, -2.75, -2.6])
mesh.AddLine('y', [-4.3, -4.15, -4])
mesh.AddLine('x', [-3.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4.2])
mesh.AddLine('y', [-4.6])

mesh.SmoothMeshLines('x', 6.25, ratio=1.5)
mesh.SmoothMeshLines('y', 6.25, ratio=1.5)
mesh.SmoothMeshLines('z', 0.5, ratio=1.4)

# --- Run Simulation ---
sim_path = sim_data_dir
os.makedirs(sim_path, exist_ok=True)
csx.Write2XML(os.path.join(sim_path, 'antenna.xml'))
sim.SetCSX(csx)
if not post_only:
    print('Starting openEMS simulation...')
    sim.Run(sim_path, verbose=2)
else:
    print('Post-processing only (--post-only mode)')

# --- Post-Processing: S11 ---
freq = np.linspace(1000000000, 6000000000, 501)
for p in ports:
    p.CalcPort(sim_path, freq)

if len(ports) == 0:
    print('[ERROR] No ports defined – cannot compute S11.')
    sys.exit(1)

s11_dB = 20 * np.log10(np.abs(ports[0].uf_ref / ports[0].uf_inc))
idx_min = np.argmin(s11_dB)
print(f'Resonance: {freq[idx_min]/1e9:.4f} GHz,  S11 = {s11_dB[idx_min]:.2f} dB')

# --- Save S11 CSV ---
csv_path = os.path.join(results_dir, 'S11.csv')
np.savetxt(csv_path, np.column_stack((freq / 1e9, s11_dB)),
           delimiter=',', header='Frequency_GHz,S11_dB', comments='')
print(f'S11 data saved to {csv_path}')

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.plot(freq / 1e9, s11_dB, 'b-', linewidth=1.5)
    ax.set_xlabel('Frequency (GHz)')
    ax.set_ylabel('S11 (dB)')
    ax.set_title('Return Loss')
    ax.grid(True)
    ax.axhline(-10, color='r', linestyle='--', alpha=0.5, label='-10 dB')
    ax.legend()
    plot_path = os.path.join(results_dir, 'S11.png')
    fig.savefig(plot_path, dpi=150)
    plt.close(fig)
    print(f'S11 plot saved to {plot_path}')
except ImportError:
    print('matplotlib not available - skipping plot.')

