# ============================================================
# Auto-generated openEMS simulation script
# Generated by AntennaSimulatorApp
# ============================================================

import os, sys
import numpy as np

post_only = '--post-only' in sys.argv

# --- Locate openEMS ---
script_dir = os.path.dirname(os.path.abspath(__file__))
sim_base = os.path.dirname(script_dir)  # Sim/
geometry_dir = os.path.join(sim_base, 'geometry')
sim_data_dir = os.path.join(sim_base, 'sim_data')
results_dir  = os.path.join(sim_base, 'results')

openems_path = r'C:\Users\Bin Xiao\OneDrive\Desktop\PCBAntSim\openEMS'
if openems_path and os.path.isdir(openems_path):
    os.add_dll_directory(openems_path)
    print(f'openEMS found: {openems_path}')
else:
    print('WARNING: openEMS folder not found, relying on system PATH')

from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import *

# --- Simulation Parameters ---
unit = 1e-3  # all coordinates in mm
f_start = 1000000000
f_stop  = 6000000000
f0      = 3500000000

# --- FDTD Setup ---
sim = openEMS(NrTS=200000, EndCriteria=1E-05)
sim.SetGaussExcite(f0, (f_stop - f_start) / 2)
sim.SetBoundaryCond(['PML_8', 'PML_8', 'PML_8', 'PML_8', 'PML_8', 'PML_8'])

csx = ContinuousStructure()
mesh = csx.GetGrid()
mesh.SetDeltaUnit(unit)

# --- Materials ---
copper = csx.AddMetal('Copper')
mat_fr4 = csx.AddMaterial('mat_fr4', epsilon=4.3, kappa=0.02)

# --- Carrier Board Geometry ---
mat_fr4.AddBox([-30, -40, -0.2], [30, 0, 0], priority=0)
mat_fr4.AddBox([-30, -40, -1.46], [30, 0, -0.2], priority=0)

# carrier_CARRIER_L2_GND_main_0
copper.AddPolygon(np.array([[-30, -30, 30, 30, 15, 15, -15, -15], [0, -40, -40, 0, 0, -4, -4, 0]]), 'z', -0.2, priority=12)
# carrier_CARRIER_TOP_GND_main_1
copper.AddPolygon(np.array([[-30, -30, 30, 30, 15, 15, -2.5, -2.5, -3, -3, -15, -15], [0, -40, -40, 0, 0, -4, -4, -4.5, -4.5, -4, -4, 0]]), 'z', 0, priority=12)
# carrier_Ant_main_2
copper.AddPolygon(np.array([[4.1, 4.4, 4.4, 4.1], [-3.2, -3.2, -3.85, -3.85]]), 'z', 0, priority=12)
# carrier_Antenna (MIFA)_main_3
copper.AddPolygon(np.array([[-4.6, -3.3, -3.3, -4.6], [-4.3, -4.3, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_0
copper.AddPolygon(np.array([[-4.6, -2.6, -2.6, -4.6], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_1
copper.AddPolygon(np.array([[-2.9, -2.6, -2.6, -2.9], [-4.3, -4.3, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_2
copper.AddPolygon(np.array([[-2.9, -1.6, -1.6, -2.9], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_3
copper.AddPolygon(np.array([[-1.9, -1.6, -1.6, -1.9], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_4
copper.AddPolygon(np.array([[-1.9, -0.6, -0.6, -1.9], [-3.55, -3.55, -3.25, -3.25]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_5
copper.AddPolygon(np.array([[-0.9, -0.6, -0.6, -0.9], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_6
copper.AddPolygon(np.array([[-0.9, 0.4, 0.4, -0.9], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_7
copper.AddPolygon(np.array([[0.1, 0.4, 0.4, 0.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_8
copper.AddPolygon(np.array([[0.1, 1.4, 1.4, 0.1], [-3.55, -3.55, -3.25, -3.25]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_9
copper.AddPolygon(np.array([[1.1, 1.4, 1.4, 1.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_10
copper.AddPolygon(np.array([[1.1, 2.4, 2.4, 1.1], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_11
copper.AddPolygon(np.array([[2.1, 2.4, 2.4, 2.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_12
copper.AddPolygon(np.array([[2.1, 3.4, 3.4, 2.1], [-3.55, -3.55, -3.25, -3.25]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_13
copper.AddPolygon(np.array([[3.1, 3.4, 3.4, 3.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_14
copper.AddPolygon(np.array([[3.1, 4.4, 4.4, 3.1], [-0.4, -0.4, -0.1, -0.1]]), 'z', 0, priority=15)
# carrier_Antenna (MIFA)_merged_3_15
copper.AddPolygon(np.array([[4.1, 4.4, 4.4, 4.1], [-3.3, -3.3, -0.1, -0.1]]), 'z', 0, priority=15)
# --- Vias ---
copper.AddCylinder([-3.6, -4.6, -1.46], [-3.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-4.2, -4.6, -1.46], [-4.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-4.8, -4.6, -1.46], [-4.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-5.4, -4.6, -1.46], [-5.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-6, -4.6, -1.46], [-6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-6.6, -4.6, -1.46], [-6.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-7.2, -4.6, -1.46], [-7.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-7.8, -4.6, -1.46], [-7.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-8.4, -4.6, -1.46], [-8.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-9, -4.6, -1.46], [-9, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-9.6, -4.6, -1.46], [-9.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-10.2, -4.6, -1.46], [-10.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-3, -4.6, -1.46], [-3, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-2.4, -4.6, -1.46], [-2.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-1.8, -4.6, -1.46], [-1.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-1.2, -4.6, -1.46], [-1.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-0.6, -4.6, -1.46], [-0.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([0, -4.6, -1.46], [0, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([0.6, -4.6, -1.46], [0.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([1.2, -4.6, -1.46], [1.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([1.8, -4.6, -1.46], [1.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([2.4, -4.6, -1.46], [2.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([3, -4.6, -1.46], [3, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([3.6, -4.6, -1.46], [3.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([4.2, -4.6, -1.46], [4.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([4.8, -4.6, -1.46], [4.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([5.4, -4.6, -1.46], [5.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([6, -4.6, -1.46], [6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([6.6, -4.6, -1.46], [6.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([7.2, -4.6, -1.46], [7.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([7.8, -4.6, -1.46], [7.8, -4.6, 0], 0.1524, priority=15)

# --- Ports ---
from openEMS.ports import LumpedPort
ports = []
ports.append(LumpedPort(csx, 1, 50, [-2.9, -4.3, -0.2], [-2.6, -4, 0], 2, 1.0, priority=50))

# --- Mesh ---
mesh.AddLine('x', [-40, -30, 30, 40])
mesh.AddLine('y', [-50, -40, 0, 10])
mesh.AddLine('z', [-11.46, -1.46, -0.2, 0, 10])
mesh.AddLine('x', [-2.9, -2.75, -2.6])
mesh.AddLine('y', [-4.3, -4.15, -4])
mesh.AddLine('x', [-3.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-5.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-6.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-7.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-7.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-8.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-9])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-9.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-10.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-2.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-1.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-1.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-0.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [0])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [0.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [1.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [1.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [2.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [3.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [4.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [4.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [5.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [6.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [7.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [7.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-30, -15, -14.653333, -14.306667, -13.96, -13.613333, -13.266667, -12.92, -12.573333, -12.226667, -11.88, -11.533333, -11.186667, -10.84, -10.493333, -10.146667, -9.8, -9.453333, -9.106667, -8.76, -8.413333, -8.066667, -7.72, -7.373333, -7.026667, -6.68, -6.333333, -5.986667, -5.64, -5.293333, -4.946667, -4.6, -4.455556, -4.311111, -4.166667, -4.022222, -3.877778, -3.733333, -3.588889, -3.444444, -3.3, -3.2, -3.1, -3, -2.95, -2.9, -2.8, -2.7, -2.6, -2.55, -2.5, -2.3, -2.1, -1.9, -1.8, -1.7, -1.6, -1.483333, -1.366667, -1.25, -1.133333, -1.016667, -0.9, -0.8, -0.7, -0.6, -0.483333, -0.366667, -0.25, -0.133333, -0.016667, 0.1, 0.2, 0.3, 0.4, 0.516667, 0.633333, 0.75, 0.866667, 0.983333, 1.1, 1.2, 1.3, 1.4, 1.516667, 1.633333, 1.75, 1.866667, 1.983333, 2.1, 2.2, 2.3, 2.4, 2.516667, 2.633333, 2.75, 2.866667, 2.983333, 3.1, 3.2, 3.3, 3.4, 3.516667, 3.633333, 3.75, 3.866667, 3.983333, 4.1, 4.2, 4.3, 4.4, 4.753333, 5.106667, 5.46, 5.813333, 6.166667, 6.52, 6.873333, 7.226667, 7.58, 7.933333, 8.286667, 8.64, 8.993333, 9.346667, 9.7, 10.053333, 10.406667, 10.76, 11.113333, 11.466667, 11.82, 12.173333, 12.526667, 12.88, 13.233333, 13.586667, 13.94, 14.293333, 14.646667, 15, 30])
mesh.AddLine('y', [-40, -4.5, -4.433333, -4.366667, -4.3, -4.25, -4.2, -4.15, -4.1, -4.05, -4, -3.95, -3.9, -3.85, -3.8, -3.75, -3.7, -3.65, -3.6, -3.55, -3.4875, -3.425, -3.3625, -3.3, -3.25, -3.2, -3.106667, -3.013333, -2.92, -2.826667, -2.733333, -2.64, -2.546667, -2.453333, -2.36, -2.266667, -2.173333, -2.08, -1.986667, -1.893333, -1.8, -1.706667, -1.613333, -1.52, -1.426667, -1.333333, -1.24, -1.146667, -1.053333, -0.96, -0.866667, -0.773333, -0.68, -0.586667, -0.493333, -0.4, -0.35, -0.3, -0.25, -0.2, -0.15, -0.1, -0.05, 0])

mesh.SmoothMeshLines('x', 6.25, ratio=1.5)
mesh.SmoothMeshLines('y', 6.25, ratio=1.5)
mesh.SmoothMeshLines('z', 0.5, ratio=1.4)

# --- Run Simulation ---
sim_path = sim_data_dir
os.makedirs(sim_path, exist_ok=True)
csx.Write2XML(os.path.join(sim_path, 'antenna.xml'))
sim.SetCSX(csx)

if not post_only:
    print('Starting openEMS simulation...')
    sim.Run(sim_path, verbose=2, numThreads=8)
else:
    print('Post-processing only (--post-only mode)')

# --- Post-Processing: S11 ---
freq = np.linspace(1000000000, 6000000000, 501)
try:
    for p in ports:
        p.CalcPort(sim_path, freq)
except Exception as e:
    print(f'[WARN] Port data not ready yet: {e}')
    sys.exit(0)

if len(ports) == 0:
    print('[ERROR] No ports defined – cannot compute S11.')
    sys.exit(1)

s11_dB = 20 * np.log10(np.abs(ports[0].uf_ref / ports[0].uf_inc))
s11_complex = ports[0].uf_ref / ports[0].uf_inc
idx_min = np.argmin(s11_dB)
print(f'Resonance: {freq[idx_min]/1e9:.4f} GHz,  S11 = {s11_dB[idx_min]:.2f} dB')

# --- Save S11 CSV ---
csv_path = os.path.join(results_dir, 'S11.csv')
np.savetxt(csv_path, np.column_stack((freq / 1e9, s11_dB, np.real(s11_complex), np.imag(s11_complex))),
           delimiter=',', header='Frequency_GHz,S11_dB,S11_Real,S11_Imag', comments='')
print(f'S11 data saved to {csv_path}')

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.plot(freq / 1e9, s11_dB, 'b-', linewidth=1.5)
    ax.set_xlabel('Frequency (GHz)')
    ax.set_ylabel('S11 (dB)')
    ax.set_title('Return Loss')
    ax.grid(True)
    ax.axhline(-10, color='r', linestyle='--', alpha=0.5, label='-10 dB')
    ax.legend()
    plot_path = os.path.join(results_dir, 'S11.png')
    fig.savefig(plot_path, dpi=150)
    plt.close(fig)
    print(f'S11 plot saved to {plot_path}')
except ImportError:
    print('matplotlib not available - skipping plot.')

