# ============================================================
# Auto-generated openEMS simulation script
# Generated by AntennaSimulatorApp
# ============================================================

import os, sys
import numpy as np

post_only = '--post-only' in sys.argv

# --- Locate openEMS ---
script_dir = os.path.dirname(os.path.abspath(__file__))
sim_base = os.path.dirname(script_dir)  # Sim/
geometry_dir = os.path.join(sim_base, 'geometry')
sim_data_dir = os.path.join(sim_base, 'sim_data')
results_dir  = os.path.join(sim_base, 'results')

openems_path = r'C:\Users\abing\OneDrive\Desktop\PCBAntSim\openEMS'
if openems_path and os.path.isdir(openems_path):
    os.add_dll_directory(openems_path)
    print(f'openEMS found: {openems_path}')
else:
    print('WARNING: openEMS folder not found, relying on system PATH')

from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import *

# --- Simulation Parameters ---
unit = 1e-3  # all coordinates in mm
f_start = 1000000000
f_stop  = 4000000000
f0      = 2500000000

# --- FDTD Setup ---
sim = openEMS(NrTS=200000, EndCriteria=1E-05)
sim.SetGaussExcite(f0, (f_stop - f_start) / 2)
sim.SetBoundaryCond(['PML_4', 'PML_4', 'PML_4', 'PML_4', 'PML_4', 'PML_4'])

csx = ContinuousStructure()
mesh = csx.GetGrid()
mesh.SetDeltaUnit(unit)

# --- Materials ---
copper = csx.AddMetal('Copper')
mat_soldermask = csx.AddMaterial('mat_soldermask', epsilon=3.8, kappa=0.02)
mat_fr4 = csx.AddMaterial('mat_fr4', epsilon=4.3, kappa=0.02)

# --- Carrier Board Geometry ---
mat_soldermask.AddBox([-30, -40, -0.025], [30, 0, 0], priority=0)
mat_fr4.AddBox([-30, -40, -0.225], [30, 0, -0.025], priority=0)
mat_fr4.AddBox([-30, -40, -1.51], [30, 0, -0.225], priority=0)

# carrier_CARRIER_L2_GND_main_0
copper.AddPolygon(np.array([[-30, -30, 30, 30, 15, 15, -15, -15], [0, -40, -40, 0, 0, -4, -4, 0]]), 'z', -0.225, priority=12)
# carrier_CARRIER_TOP_GND_main_1
copper.AddPolygon(np.array([[-30, -30, 30, 30, 15, 15, -2.5, -2.5, -3, -3, -15, -15], [0, -40, -40, 0, 0, -4, -4, -4.5, -4.5, -4, -4, 0]]), 'z', -0.025, priority=12)
# --- RF Module Geometry ---
mat_soldermask.AddBox([-5.1, -15, 0.1], [5.1, -0, 0.125], priority=0)
mat_fr4.AddBox([-5.1, -15, 0.125], [5.1, -0, 0.415], priority=0)
mat_fr4.AddBox([-5.1, -15, 0.415], [5.1, -0, 0.515], priority=0)
mat_soldermask.AddBox([-5.1, -15, 0.515], [5.1, -0, 0.54], priority=0)

# module_MODULE_L3_GND_main_0
copper.AddPolygon(np.array([[-5.1, -5.1, 5.1, 5.1], [-4, -15, -15, -4]]), 'z', 0.415, priority=12)
# module_MODULE_TOP_GND_main_1
copper.AddPolygon(np.array([[-3.3, 5.1, 5.1, -3.07, -3.07, -3.77, -3.77, -5.1, -5.1], [-7, -7, -4.4, -4.4, -4.6, -4.6, -4, -4, -7]]), 'z', 0.515, priority=12)
# module_MODULE_BOT_main_2
copper.AddPolygon(np.array([[-5.1, -5.1, 5.1, 5.1], [-4, -15, -15, -4]]), 'z', 0.125, priority=12)
# module_Antenna (MIFA)_main_3
copper.AddPolygon(np.array([[-4.17, -3.87, -3.87, -4.17], [-4.35, -4.35, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_0
copper.AddPolygon(np.array([[-4.17, -3.22, -3.22, -4.17], [-0.65, -0.65, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_1
copper.AddPolygon(np.array([[-3.62, -3.22, -3.22, -3.62], [-4.35, -4.35, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_2
copper.AddPolygon(np.array([[-3.62, -2.07, -2.07, -3.62], [-0.65, -0.65, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_3
copper.AddPolygon(np.array([[-2.47, -2.07, -2.07, -2.47], [-3.45, -3.45, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_4
copper.AddPolygon(np.array([[-2.47, -0.92, -0.92, -2.47], [-3.45, -3.45, -3.05, -3.05]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_5
copper.AddPolygon(np.array([[-1.32, -0.92, -0.92, -1.32], [-3.45, -3.45, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_6
copper.AddPolygon(np.array([[-1.32, 0.23, 0.23, -1.32], [-0.65, -0.65, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_7
copper.AddPolygon(np.array([[-0.17, 0.23, 0.23, -0.17], [-3.45, -3.45, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_8
copper.AddPolygon(np.array([[-0.17, 1.38, 1.38, -0.17], [-3.45, -3.45, -3.05, -3.05]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_9
copper.AddPolygon(np.array([[0.98, 1.38, 1.38, 0.98], [-3.45, -3.45, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_10
copper.AddPolygon(np.array([[0.98, 2.53, 2.53, 0.98], [-0.65, -0.65, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_11
copper.AddPolygon(np.array([[2.13, 2.53, 2.53, 2.13], [-3.45, -3.45, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_12
copper.AddPolygon(np.array([[2.13, 3.68, 3.68, 2.13], [-3.45, -3.45, -3.05, -3.05]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_13
copper.AddPolygon(np.array([[3.28, 3.68, 3.68, 3.28], [-3.45, -3.45, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_14
copper.AddPolygon(np.array([[3.28, 4.83, 4.83, 3.28], [-0.65, -0.65, -0.25, -0.25]]), 'z', 0.515, priority=15)
# module_Antenna (MIFA)_merged_3_15
copper.AddPolygon(np.array([[4.43, 4.83, 4.83, 4.43], [-3.2, -3.2, -0.25, -0.25]]), 'z', 0.515, priority=15)
# --- Vias ---
copper.AddCylinder([-4.8, -4.6, 0.125], [-4.8, -4.6, 0.515], 0.1524, priority=15)
copper.AddCylinder([-4.2, -4.6, 0.125], [-4.2, -4.6, 0.515], 0.1524, priority=15)
copper.AddCylinder([-2, -4.6, 0.125], [-2, -4.6, 0.515], 0.1524, priority=15)
copper.AddCylinder([-1, -4.6, 0.125], [-1, -4.6, 0.515], 0.1524, priority=15)
copper.AddCylinder([0, -4.6, 0.125], [0, -4.6, 0.515], 0.1524, priority=15)
copper.AddCylinder([1, -4.6, 0.125], [1, -4.6, 0.515], 0.1524, priority=15)
copper.AddCylinder([2, -4.6, 0.125], [2, -4.6, 0.515], 0.1524, priority=15)
copper.AddCylinder([3, -4.6, 0.125], [3, -4.6, 0.515], 0.1524, priority=15)
copper.AddCylinder([4, -4.6, 0.125], [4, -4.6, 0.515], 0.1524, priority=15)
copper.AddCylinder([0, -4.6, -1.485], [0, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([1, -4.6, -1.485], [1, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([2, -4.6, -1.485], [2, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([3, -4.6, -1.485], [3, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([4, -4.6, -1.485], [4, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([5, -4.6, -1.485], [5, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([6, -4.6, -1.485], [6, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([7, -4.6, -1.485], [7, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([8, -4.6, -1.485], [8, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([9, -4.6, -1.485], [9, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([10, -4.6, -1.485], [10, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-1, -4.6, -1.485], [-1, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-2, -4.6, -1.485], [-2, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-3, -4.6, -1.485], [-3, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-4, -4.6, -1.485], [-4, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-5, -4.6, -1.485], [-5, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-6, -4.6, -1.485], [-6, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-7, -4.6, -1.485], [-7, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-8, -4.6, -1.485], [-8, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-9, -4.6, -1.485], [-9, -4.6, -0.025], 0.254, priority=15)
copper.AddCylinder([-10, -4.6, -1.485], [-10, -4.6, -0.025], 0.254, priority=15)

# --- Solder Joints (module bottom → carrier top) ---
copper.AddCylinder([0, -4.6, -0.025], [0, -4.6, 0.125], 0.381, priority=15)
copper.AddCylinder([2, -4.6, -0.025], [2, -4.6, 0.125], 0.381, priority=15)
copper.AddCylinder([4, -4.6, -0.025], [4, -4.6, 0.125], 0.381, priority=15)
copper.AddCylinder([-2, -4.6, -0.025], [-2, -4.6, 0.125], 0.381, priority=15)
copper.AddCylinder([-4, -4.6, -0.025], [-4, -4.6, 0.125], 0.381, priority=15)

# --- Ports ---
from openEMS.ports import LumpedPort
ports = []
ports.append(LumpedPort(csx, 1, 50, [-3.62, -4.35, 0.415], [-3.22, -3.95, 0.515], 2, 1.0, priority=50))

# --- Mesh ---
mesh.AddLine('x', [-60, -30, 30, 60])
mesh.AddLine('y', [-70, -40, 0, 30])
mesh.AddLine('z', [-31.51, -1.51, -0.225, -0.025, 0, 0.1, 0.125, 0.415, 0.515, 0.54, 30.54])
mesh.AddLine('x', [-5.1, 5.1])
mesh.AddLine('y', [-15, -0])
mesh.AddLine('x', [-3.62, -3.42, -3.22])
mesh.AddLine('y', [-4.35, -4.15, -3.95])
mesh.AddLine('x', [-4.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-1])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [0])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [1])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [0])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [1])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [5])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [7])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [9])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [10])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-1])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-5])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-7])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-9])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-10])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-30, -15, -14.67, -14.34, -14.01, -13.68, -13.35, -13.02, -12.69, -12.36, -12.03, -11.7, -11.37, -11.04, -10.71, -10.38, -10.05, -9.72, -9.39, -9.06, -8.73, -8.4, -8.07, -7.74, -7.41, -7.08, -6.75, -6.42, -6.09, -5.76, -5.43, -5.1, -4.945, -4.79, -4.635, -4.48, -4.325, -4.17, -4.07, -3.97, -3.87, -3.77, -3.62, -3.513333, -3.406667, -3.3, -3.07, -2.833333, -2.666667, -2.5, -2.336667, -2.203333, -2.07, -1.945, -1.82, -1.695, -1.57, -1.445, -1.32, -1.186667, -1.053333, -0.92, -0.795, -0.67, -0.545, -0.42, -0.295, -0.17, -0.036667, 0.096667, 0.23, 0.355, 0.48, 0.605, 0.73, 0.855, 0.98, 1.113333, 1.246667, 1.38, 1.505, 1.63, 1.755, 1.88, 2.005, 2.13, 2.263333, 2.396667, 2.53, 2.655, 2.78, 2.905, 3.03, 3.155, 3.28, 3.413333, 3.546667, 3.68, 3.805, 3.93, 4.055, 4.18, 4.305, 4.43, 4.563333, 4.696667, 4.83, 4.965, 5.1, 5.43, 5.76, 6.09, 6.42, 6.75, 7.08, 7.41, 7.74, 8.07, 8.4, 8.73, 9.06, 9.39, 9.72, 10.05, 10.38, 10.71, 11.04, 11.37, 11.7, 12.03, 12.36, 12.69, 13.02, 13.35, 13.68, 14.01, 14.34, 14.67, 15, 30])
mesh.AddLine('y', [-40, -15, -14.733333, -14.466667, -14.2, -13.933333, -13.666667, -13.4, -13.133333, -12.866667, -12.6, -12.333333, -12.066667, -11.8, -11.533333, -11.266667, -11, -10.733333, -10.466667, -10.2, -9.933333, -9.666667, -9.4, -9.133333, -8.866667, -8.6, -8.333333, -8.066667, -7.8, -7.533333, -7.266667, -7, -6.9, -6.8, -6.7, -6.6, -6.5, -6.4, -6.3, -6.2, -6.1, -6, -5.9, -5.8, -5.7, -5.6, -5.5, -5.4, -5.3, -5.2, -5.1, -5, -4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.175, -4, -3.8625, -3.725, -3.5875, -3.45, -3.325, -3.2, -3.05, -2.95, -2.85, -2.75, -2.65, -2.55, -2.45, -2.35, -2.25, -2.15, -2.05, -1.95, -1.85, -1.75, -1.65, -1.55, -1.45, -1.35, -1.25, -1.15, -1.05, -0.95, -0.85, -0.75, -0.65, -0.55, -0.45, -0.35, -0.25, -0.125, 0])

mesh.SmoothMeshLines('x', 6.25, ratio=1.5)
mesh.SmoothMeshLines('y', 6.25, ratio=1.5)
mesh.SmoothMeshLines('z', 1, ratio=1.4)

# --- Field Dumps (frequency domain, 2-D XY slice) ---
_fd_f0 = f0  # dump frequency

Jf_dump = csx.AddDump('Jf_surface', dump_type=12, dump_mode=2, file_type=1)
Jf_dump.SetFrequency(_fd_f0)
Jf_dump.AddBox([-30, -40, 0.54], [30, 0, 0.54])

Ef_dump = csx.AddDump('Ef_surface', dump_type=10, dump_mode=2, file_type=1)
Ef_dump.SetFrequency(_fd_f0)
Ef_dump.AddBox([-30, -40, 0.54], [30, 0, 0.54])

Hf_dump = csx.AddDump('Hf_surface', dump_type=11, dump_mode=2, file_type=1)
Hf_dump.SetFrequency(_fd_f0)
Hf_dump.AddBox([-30, -40, 0.54], [30, 0, 0.54])

# --- Run Simulation ---
sim_path = sim_data_dir
os.makedirs(sim_path, exist_ok=True)
csx.Write2XML(os.path.join(sim_path, 'antenna.xml'))
sim.SetCSX(csx)

# --- NF2FF Recording Box ---
from openEMS.nf2ff import nf2ff
nf2ff_box = sim.CreateNF2FFBox()

if not post_only:
    print('Starting openEMS simulation...')
    sim.Run(sim_path, verbose=2, numThreads=16, engine='multithreaded')
else:
    print('Post-processing only (--post-only mode)')

# --- Post-Processing: S11 ---
freq = np.linspace(1000000000, 4000000000, 501)
try:
    for p in ports:
        p.CalcPort(sim_path, freq)
except Exception as e:
    print(f'[WARN] Port data not ready yet: {e}')
    sys.exit(0)

if len(ports) == 0:
    print('[ERROR] No ports defined – cannot compute S11.')
    sys.exit(1)

s11_dB = 20 * np.log10(np.abs(ports[0].uf_ref / ports[0].uf_inc))
s11_complex = ports[0].uf_ref / ports[0].uf_inc
idx_min = np.argmin(s11_dB)
print(f'Resonance: {freq[idx_min]/1e9:.4f} GHz,  S11 = {s11_dB[idx_min]:.2f} dB')

# --- Save S11 CSV ---
csv_path = os.path.join(results_dir, 'S11.csv')
np.savetxt(csv_path, np.column_stack((freq / 1e9, s11_dB, np.real(s11_complex), np.imag(s11_complex))),
           delimiter=',', header='Frequency_GHz,S11_dB,S11_Real,S11_Imag', comments='')
print(f'S11 data saved to {csv_path}')

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.plot(freq / 1e9, s11_dB, 'b-', linewidth=1.5)
    ax.set_xlabel('Frequency (GHz)')
    ax.set_ylabel('S11 (dB)')
    ax.set_title('Return Loss')
    ax.grid(True)
    ax.axhline(-10, color='r', linestyle='--', alpha=0.5, label='-10 dB')
    ax.legend()
    plot_path = os.path.join(results_dir, 'S11.png')
    fig.savefig(plot_path, dpi=150)
    plt.close(fig)
    print(f'S11 plot saved to {plot_path}')
except ImportError:
    print('matplotlib not available - skipping plot.')

# --- Post-Processing: Far-Field ---
ff_freq = np.linspace(1000000000, 4000000000, 501)

try:
    _ = ports[0].uf_inc
except:
    try:
        for p in ports:
            p.CalcPort(sim_path, ff_freq)
    except Exception as e:
        print(f'[WARN] Port data not ready yet: {e}')
        sys.exit(0)

ff_s11_dB = 20 * np.log10(np.abs(ports[0].uf_ref / ports[0].uf_inc))
ff_idx_min = np.argmin(ff_s11_dB)
f_res = ff_freq[ff_idx_min]
print(f'Far-field at resonance: {f_res/1e9:.4f} GHz')

theta = np.arange(-180, 180.5, 1)
phi_E = 0    # E-plane (XZ)
phi_H = 90   # H-plane (YZ)

P_in = 0.5 * np.real(ports[0].uf_tot[ff_idx_min] * np.conj(ports[0].if_tot[ff_idx_min]))

nf2ff_res_E = nf2ff_box.CalcNF2FF(sim_path, f_res, theta, phi_E, center=[0,0,0])
E_norm = nf2ff_res_E.E_norm[0]
Dmax_E = nf2ff_res_E.Dmax[0]

nf2ff_res_H = nf2ff_box.CalcNF2FF(sim_path, f_res, theta, phi_H, center=[0,0,0])
H_norm = nf2ff_res_H.E_norm[0]
Dmax_H = nf2ff_res_H.Dmax[0]

D_E_dBi = 10 * np.log10(nf2ff_res_E.Dmax[0])
D_H_dBi = 10 * np.log10(nf2ff_res_H.Dmax[0])

if P_in > 0:
    realized_gain_E = (E_norm**2 / np.max(E_norm**2)) * nf2ff_res_E.Dmax[0]
    realized_gain_H = (H_norm**2 / np.max(H_norm**2)) * nf2ff_res_H.Dmax[0]
else:
    realized_gain_E = E_norm**2 / np.max(E_norm**2) if np.max(E_norm**2) > 0 else E_norm * 0
    realized_gain_H = H_norm**2 / np.max(H_norm**2) if np.max(H_norm**2) > 0 else H_norm * 0

E_pattern_dB = 10 * np.log10(E_norm**2 / np.max(E_norm**2) + 1e-12)
H_pattern_dB = 10 * np.log10(H_norm**2 / np.max(H_norm**2) + 1e-12)

Prad = nf2ff_res_E.Prad[0]
eff = Prad / P_in if P_in > 0 else 0
print(f'Directivity: {D_E_dBi:.2f} dBi,  Radiation Efficiency: {eff*100:.1f}%')

eplane_csv = os.path.join(results_dir, 'FarField_Eplane.csv')
np.savetxt(eplane_csv, np.column_stack((theta, E_pattern_dB)),
           delimiter=',', header='Theta_deg,Pattern_dB', comments='')
print(f'E-plane pattern saved to {eplane_csv}')

hplane_csv = os.path.join(results_dir, 'FarField_Hplane.csv')
np.savetxt(hplane_csv, np.column_stack((theta, H_pattern_dB)),
           delimiter=',', header='Theta_deg,Pattern_dB', comments='')
print(f'H-plane pattern saved to {hplane_csv}')

summary_csv = os.path.join(results_dir, 'FarField_Summary.csv')
with open(summary_csv, 'w') as f:
    f.write('Parameter,Value\n')
    f.write(f'Frequency_GHz,{f_res/1e9:.6f}\n')
    f.write(f'Directivity_dBi,{D_E_dBi:.4f}\n')
    f.write(f'RadiationEfficiency,{eff:.6f}\n')
    f.write(f'Prad_W,{Prad:.6e}\n')
    f.write(f'Pin_W,{P_in:.6e}\n')
print(f'Far-field summary saved to {summary_csv}')

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    # --- Rectangular pattern plot ---
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(theta, E_pattern_dB, 'b-', linewidth=1.5, label='E-plane')
    ax.plot(theta, H_pattern_dB, 'r--', linewidth=1.5, label='H-plane')
    ax.set_xlabel('Theta (degrees)')
    ax.set_ylabel('Normalized Pattern (dB)')
    ax.set_title(f'Far-Field Pattern @ {f_res/1e9:.3f} GHz')
    ax.set_ylim([-40, 5])
    ax.grid(True)
    ax.legend()
    fig.savefig(os.path.join(results_dir, 'FarField_Rectangular.png'), dpi=150)
    plt.close(fig)

    # --- Polar pattern plot ---
    fig, (ax1, ax2) = plt.subplots(1, 2, subplot_kw={'polar': True}, figsize=(12, 5))
    theta_rad = np.deg2rad(theta)
    ax1.plot(theta_rad, np.clip(E_pattern_dB, -40, 0) + 40, 'b-', linewidth=1.5)
    ax1.set_title('E-plane', pad=15)
    ax1.set_ylim([0, 40])
    ax2.plot(theta_rad, np.clip(H_pattern_dB, -40, 0) + 40, 'r-', linewidth=1.5)
    ax2.set_title('H-plane', pad=15)
    ax2.set_ylim([0, 40])
    fig.savefig(os.path.join(results_dir, 'FarField_Polar.png'), dpi=150)
    plt.close(fig)
    print('Far-field pattern plots saved.')
except ImportError:
    print('matplotlib not available - skipping far-field plots.')

# --- 3D Far-Field Pattern ---
print('Computing full 3D far-field pattern ...')
theta_3d = np.arange(0, 181, 5)
phi_3d   = np.arange(0, 361, 5)
nf2ff_3d = nf2ff_box.CalcNF2FF(sim_path, f_res, theta_3d, phi_3d, center=[0,0,0])
E3d = nf2ff_3d.E_norm[0]
E3d_max2 = np.max(E3d**2)
if E3d_max2 > 0:
    E3d_dB = 10 * np.log10(E3d**2 / E3d_max2 + 1e-12)
else:
    E3d_dB = np.zeros_like(E3d)
ff3d_csv = os.path.join(results_dir, 'FarField_3D.csv')
with open(ff3d_csv, 'w') as f3d:
    f3d.write('Theta_deg,Phi_deg,Pattern_dB\n')
    for ti in range(len(theta_3d)):
        for pi in range(len(phi_3d)):
            f3d.write(f'{theta_3d[ti]:.1f},{phi_3d[pi]:.1f},{E3d_dB[ti,pi]:.4f}\n')
print(f'3D far-field pattern saved to {ff3d_csv}')

# --- Post-Processing: Field Dump Heatmaps ---
try:
    import h5py
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm
    from matplotlib.patches import Polygon as MplPoly
except ImportError as _imp_err:
    print(f'[WARN] Skipping field plots: {_imp_err}')
    h5py = None

if h5py is not None:
    _shape_outlines = []
    _shape_outlines.append({'name': 'CARRIER_L2_GND', 'is_antenna': False, 'xy': [(-30, 0), (-30, -40), (30, -40), (30, 0), (15, 0), (15, -4), (-15, -4), (-15, 0), (-30, 0)]})
    _shape_outlines.append({'name': 'CARRIER_TOP_GND', 'is_antenna': False, 'xy': [(-30, 0), (-30, -40), (30, -40), (30, 0), (15, 0), (15, -4), (-2.5, -4), (-2.5, -4.5), (-3, -4.5), (-3, -4), (-15, -4), (-15, 0), (-30, 0)]})

    def _plot_field_dump(h5_dir, name, title, cmap='hot'):
        """Read an openEMS HDF5 field dump and save a heatmap PNG."""
        h5_path = os.path.join(sim_path, name + '.h5')
        if not os.path.isfile(h5_path):
            print(f'[WARN] Field dump not found: {h5_path}')
            return
        try:
            with h5py.File(h5_path, 'r') as hf:
                x = np.array(hf['/Mesh/x']) * 1e3  # m → mm
                y = np.array(hf['/Mesh/y']) * 1e3  # m → mm
                fd_grp = hf['/FieldData/FD']
                re = np.array(fd_grp['f0_real'])  # (3, Nz, Ny, Nx)
                im = np.array(fd_grp['f0_imag'])
                mag = np.sqrt(np.sum(re**2 + im**2, axis=0))
                mag = np.squeeze(mag)
                if mag.ndim == 1:
                    print(f'[WARN] {name}: unexpected 1D field data')
                    return
                vmax = mag.max()
                if vmax == 0:
                    print(f'[WARN] {name}: all-zero field data')
                    return
                vmin = max(vmax * 1e-3, mag[mag > 0].min()) if np.any(mag > 0) else 1e-10

                # --- Determine view bounds: prefer antenna shapes, then field data ---
                _ant_shapes = [s for s in _shape_outlines if s['is_antenna']]
                _crop_src = _ant_shapes if _ant_shapes else _shape_outlines
                if len(_crop_src) > 0:
                    all_sx = [px for s in _crop_src for px, _ in s['xy']]
                    all_sy = [py for s in _crop_src for _, py in s['xy']]
                    margin_mm = 3.0
                    x_lo = min(all_sx) - margin_mm
                    x_hi = max(all_sx) + margin_mm
                    y_lo = min(all_sy) - margin_mm
                    y_hi = max(all_sy) + margin_mm
                else:
                    active = mag >= vmin
                    rows = np.where(active.any(axis=1))[0]
                    cols = np.where(active.any(axis=0))[0]
                    if len(rows) > 0 and len(cols) > 0:
                        margin_mm = 5.0
                        x_lo = x[max(cols[0]-1, 0)] - margin_mm
                        x_hi = x[min(cols[-1]+1, len(x)-1)] + margin_mm
                        y_lo = y[max(rows[0]-1, 0)] - margin_mm
                        y_hi = y[min(rows[-1]+1, len(y)-1)] + margin_mm
                    else:
                        x_lo, x_hi = x[0], x[-1]
                        y_lo, y_hi = y[0], y[-1]

                fig, ax = plt.subplots(figsize=(10, 8))
                pcm = ax.pcolormesh(x, y, mag, shading='auto', cmap=cmap,
                                    norm=LogNorm(vmin=vmin, vmax=vmax))
                ax.set_xlim(x_lo, x_hi)
                ax.set_ylim(y_lo, y_hi)

                # --- Overlay shape outlines ---
                for shp in _shape_outlines:
                    ec = 'lime' if shp['is_antenna'] else 'cyan'
                    lw = 1.5 if shp['is_antenna'] else 0.8
                    poly = MplPoly(shp['xy'], closed=True, fill=False,
                                   edgecolor=ec, linewidth=lw, linestyle='-')
                    ax.add_patch(poly)

                ax.set_xlabel('X (mm)')
                ax.set_ylabel('Y (mm)')
                ax.set_title(title)
                ax.set_aspect('equal')
                plt.colorbar(pcm, ax=ax, label='Magnitude')
                plt.tight_layout()
                png_path = os.path.join(results_dir, name + '.png')
                fig.savefig(png_path, dpi=150)
                plt.close(fig)
                print(f'Field plot saved: {png_path}')
                csv_path = os.path.join(results_dir, name + '.csv')
                with open(csv_path, 'w') as csvf:
                    csvf.write('# x_coords: ' + ','.join(f'{v:.6g}' for v in x) + '\n')
                    csvf.write('# y_coords: ' + ','.join(f'{v:.6g}' for v in y) + '\n')
                    for row_i in range(mag.shape[0]):
                        csvf.write(','.join(f'{v:.6e}' for v in mag[row_i, :]) + '\n')
        except Exception as ex:
            print(f'[WARN] Failed to plot {name}: {ex}')

    _plot_field_dump(sim_path, 'Jf_surface', 'Surface Current Density |J| (A/m)', 'hot')
    _plot_field_dump(sim_path, 'Ef_surface', 'Electric Field |E| (V/m)', 'viridis')
    _plot_field_dump(sim_path, 'Hf_surface', 'Magnetic Field |H| (A/m)', 'inferno')

