# ============================================================
# Auto-generated openEMS simulation script
# Generated by AntennaSimulatorApp
# ============================================================

import os, sys
import numpy as np

post_only = '--post-only' in sys.argv

# --- Locate openEMS ---
script_dir = os.path.dirname(os.path.abspath(__file__))
sim_base = os.path.dirname(script_dir)  # Sim/
geometry_dir = os.path.join(sim_base, 'geometry')
sim_data_dir = os.path.join(sim_base, 'sim_data')
results_dir  = os.path.join(sim_base, 'results')

openems_path = r'C:\Users\Bin Xiao\OneDrive\Desktop\PCBAntSim\openEMS'
if openems_path and os.path.isdir(openems_path):
    os.add_dll_directory(openems_path)
    print(f'openEMS found: {openems_path}')
else:
    print('WARNING: openEMS folder not found, relying on system PATH')

from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import *

# --- Simulation Parameters ---
unit = 1e-3  # all coordinates in mm
f_start = 1000000000
f_stop  = 6000000000
f0      = 3500000000

# --- FDTD Setup ---
sim = openEMS(NrTS=200000, EndCriteria=1E-05)
sim.SetGaussExcite(f0, (f_stop - f_start) / 2)
sim.SetBoundaryCond(['PML_8', 'PML_8', 'PML_8', 'PML_8', 'PML_8', 'PML_8'])

csx = ContinuousStructure()
mesh = csx.GetGrid()
mesh.SetDeltaUnit(unit)

# --- Materials ---
copper = csx.AddMetal('Copper')
mat_fr4 = csx.AddMaterial('mat_fr4', epsilon=4.3, kappa=0.02)

# --- Carrier Board Geometry ---
mat_fr4.AddBox([-40, -100, -0.235], [40, 0, -0.035], priority=0)
mat_fr4.AddBox([-40, -100, -1.33], [40, 0, -0.27], priority=0)
mat_fr4.AddBox([-40, -100, -1.565], [40, 0, -1.365], priority=0)

# carrier_CARRIER_L2_GND_main_0
copper.AddLinPoly(np.array([[-40, -40, 40, 40, 15, 15, -15, -15], [0, -100, -100, 0, 0, -4, -4, 0]]), 'z', -0.27, 0.035, priority=12)
# carrier_CARRIER_TOP_GND_main_1
copper.AddLinPoly(np.array([[-40, -40, 40, 40, 15, 15, -2.5, -2.5, -3, -3, -15, -15], [0, -100, -100, 0, 0, -4, -4, -4.5, -4.5, -4, -4, 0]]), 'z', -0.035, 0.035, priority=12)
# carrier_Ant_main_2
copper.AddLinPoly(np.array([[4.1, 4.4, 4.4, 4.1], [-3.2, -3.2, -3.85, -3.85]]), 'z', -0.035, 0.035, priority=12)
# carrier_Antenna (MIFA)_main_3
copper.AddLinPoly(np.array([[-4.6, -3.3, -3.3, -4.6], [-4.3, -4.3, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_0
copper.AddLinPoly(np.array([[-4.6, -2.6, -2.6, -4.6], [-0.4, -0.4, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_1
copper.AddLinPoly(np.array([[-2.9, -2.6, -2.6, -2.9], [-4.3, -4.3, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_2
copper.AddLinPoly(np.array([[-2.9, -1.6, -1.6, -2.9], [-0.4, -0.4, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_3
copper.AddLinPoly(np.array([[-1.9, -1.6, -1.6, -1.9], [-3.55, -3.55, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_4
copper.AddLinPoly(np.array([[-1.9, -0.6, -0.6, -1.9], [-3.55, -3.55, -3.25, -3.25]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_5
copper.AddLinPoly(np.array([[-0.9, -0.6, -0.6, -0.9], [-3.55, -3.55, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_6
copper.AddLinPoly(np.array([[-0.9, 0.4, 0.4, -0.9], [-0.4, -0.4, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_7
copper.AddLinPoly(np.array([[0.1, 0.4, 0.4, 0.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_8
copper.AddLinPoly(np.array([[0.1, 1.4, 1.4, 0.1], [-3.55, -3.55, -3.25, -3.25]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_9
copper.AddLinPoly(np.array([[1.1, 1.4, 1.4, 1.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_10
copper.AddLinPoly(np.array([[1.1, 2.4, 2.4, 1.1], [-0.4, -0.4, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_11
copper.AddLinPoly(np.array([[2.1, 2.4, 2.4, 2.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_12
copper.AddLinPoly(np.array([[2.1, 3.4, 3.4, 2.1], [-3.55, -3.55, -3.25, -3.25]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_13
copper.AddLinPoly(np.array([[3.1, 3.4, 3.4, 3.1], [-3.55, -3.55, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_14
copper.AddLinPoly(np.array([[3.1, 4.4, 4.4, 3.1], [-0.4, -0.4, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# carrier_Antenna (MIFA)_merged_3_15
copper.AddLinPoly(np.array([[4.1, 4.4, 4.4, 4.1], [-3.3, -3.3, -0.1, -0.1]]), 'z', -0.035, 0.035, priority=15)
# --- Vias ---
copper.AddCylinder([-3.6, -4.6, -1.6], [-3.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-4.2, -4.6, -1.6], [-4.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-4.8, -4.6, -1.6], [-4.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-5.4, -4.6, -1.6], [-5.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-6, -4.6, -1.6], [-6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-6.6, -4.6, -1.6], [-6.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-7.2, -4.6, -1.6], [-7.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-7.8, -4.6, -1.6], [-7.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-8.4, -4.6, -1.6], [-8.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-9, -4.6, -1.6], [-9, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-9.6, -4.6, -1.6], [-9.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-10.2, -4.6, -1.6], [-10.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-3, -4.6, -1.6], [-3, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-2.4, -4.6, -1.6], [-2.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-1.8, -4.6, -1.6], [-1.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-1.2, -4.6, -1.6], [-1.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([-0.6, -4.6, -1.6], [-0.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([0, -4.6, -1.6], [0, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([0.6, -4.6, -1.6], [0.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([1.2, -4.6, -1.6], [1.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([1.8, -4.6, -1.6], [1.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([2.4, -4.6, -1.6], [2.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([3, -4.6, -1.6], [3, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([3.6, -4.6, -1.6], [3.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([4.2, -4.6, -1.6], [4.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([4.8, -4.6, -1.6], [4.8, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([5.4, -4.6, -1.6], [5.4, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([6, -4.6, -1.6], [6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([6.6, -4.6, -1.6], [6.6, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([7.2, -4.6, -1.6], [7.2, -4.6, 0], 0.1524, priority=15)
copper.AddCylinder([7.8, -4.6, -1.6], [7.8, -4.6, 0], 0.1524, priority=15)

# --- Ports ---
from openEMS.ports import LumpedPort
ports = []
ports.append(LumpedPort(csx, 1, 50, [-2.9, -4.3, -0.235], [-2.6, -4, -0.035], 2, 1.0, priority=50))

# --- Mesh ---
mesh.AddLine('x', [-50, -40, 40, 50])
mesh.AddLine('y', [-110, -100, 0, 10])
mesh.AddLine('z', [-11.6, -1.6, -1.565, -1.515, -1.465, -1.415, -1.365, -1.33, -0.27, -0.235, -0.185, -0.135, -0.085, -0.035, 0, 10])
mesh.AddLine('x', [-2.9, -2.75, -2.6])
mesh.AddLine('y', [-4.3, -4.15, -4])
mesh.AddLine('x', [-3.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-4.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-5.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-6.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-7.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-7.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-8.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-9])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-9.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-10.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-2.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-1.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-1.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-0.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [0])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [0.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [1.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [1.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [2.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [3])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [3.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [4.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [4.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [5.4])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [6.6])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [7.2])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [7.8])
mesh.AddLine('y', [-4.6])
mesh.AddLine('x', [-40, -15, -13.96, -12.92, -11.88, -10.84, -9.8, -8.76, -7.72, -6.68, -5.64, -4.6, -4.166667, -3.733333, -3.3, -3, -2.9, -2.6, -2.5, -2.2, -1.9, -1.6, -1.25, -0.9, -0.6, -0.25, 0.1, 0.4, 0.75, 1.1, 1.4, 1.75, 2.1, 2.4, 2.75, 3.1, 3.4, 3.75, 4.1, 4.4, 5.46, 6.52, 7.58, 8.64, 9.7, 10.76, 11.82, 12.88, 13.94, 15, 40])
mesh.AddLine('y', [-100, -4.5, -4.4, -4.3, -4.15, -4, -3.85, -3.7, -3.55, -3.425, -3.3, -3.25, -3.2, -2.92, -2.64, -2.36, -2.08, -1.8, -1.52, -1.24, -0.96, -0.68, -0.4, -0.25, -0.1, 0])

mesh.SmoothMeshLines('x', 6.25, ratio=1.5)
mesh.SmoothMeshLines('y', 6.25, ratio=1.5)
mesh.SmoothMeshLines('z', 0.5, ratio=1.4)

# --- Run Simulation ---
sim_path = sim_data_dir
os.makedirs(sim_path, exist_ok=True)
csx.Write2XML(os.path.join(sim_path, 'antenna.xml'))
sim.SetCSX(csx)

if not post_only:
    print('Starting openEMS simulation...')
    sim.Run(sim_path, verbose=2, numThreads=8)
else:
    print('Post-processing only (--post-only mode)')

# --- Post-Processing: S11 ---
freq = np.linspace(1000000000, 6000000000, 501)
for p in ports:
    p.CalcPort(sim_path, freq)

if len(ports) == 0:
    print('[ERROR] No ports defined – cannot compute S11.')
    sys.exit(1)

s11_dB = 20 * np.log10(np.abs(ports[0].uf_ref / ports[0].uf_inc))
s11_complex = ports[0].uf_ref / ports[0].uf_inc
idx_min = np.argmin(s11_dB)
print(f'Resonance: {freq[idx_min]/1e9:.4f} GHz,  S11 = {s11_dB[idx_min]:.2f} dB')

# --- Save S11 CSV ---
csv_path = os.path.join(results_dir, 'S11.csv')
np.savetxt(csv_path, np.column_stack((freq / 1e9, s11_dB, np.real(s11_complex), np.imag(s11_complex))),
           delimiter=',', header='Frequency_GHz,S11_dB,S11_Real,S11_Imag', comments='')
print(f'S11 data saved to {csv_path}')

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.plot(freq / 1e9, s11_dB, 'b-', linewidth=1.5)
    ax.set_xlabel('Frequency (GHz)')
    ax.set_ylabel('S11 (dB)')
    ax.set_title('Return Loss')
    ax.grid(True)
    ax.axhline(-10, color='r', linestyle='--', alpha=0.5, label='-10 dB')
    ax.legend()
    plot_path = os.path.join(results_dir, 'S11.png')
    fig.savefig(plot_path, dpi=150)
    plt.close(fig)
    print(f'S11 plot saved to {plot_path}')
except ImportError:
    print('matplotlib not available - skipping plot.')

