using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Media.Media3D;
using AntennaSimulatorApp.Models;
using AntennaSimulatorApp.ViewModels;

namespace AntennaSimulatorApp.Services
{
    /// <summary>
    /// Exports the antenna design to openEMS simulation files.
    /// Folder layout under outputDir:
    ///   scripts/run_simulation.py
    ///   geometry/*.stl
    ///   sim_data/   (created at runtime by openEMS)
    ///   results/    (created at runtime for S11 plot, etc.)
    /// </summary>
    public static class OpenEmsExporter
    {
        private const double MountGap = 0.1; // mm gap between carrier and module

        private static string F(double v) =>
            v.ToString("G10", CultureInfo.InvariantCulture);

        // ── Public entry point ───────────────────────────────────────────────

        /// <summary>
        /// Export a complete openEMS simulation project to <paramref name="outputDir"/>.
        /// </summary>
        /// <param name="outputDir">Destination folder (will be created).</param>
        /// <param name="vm">Current design state.</param>
        /// <param name="getGerberData">Delegate to parse / cache Gerber files.</param>
        /// <param name="includeDefaultCopper">Export default copper pour layers.</param>
        /// <param name="includeCopperShapes">Export manually-drawn copper shapes.</param>
        /// <param name="includeAntennas">Export parametric antenna traces.</param>
        /// <param name="includeVias">Export plated through-hole vias.</param>
        public static void Export(
            string outputDir,
            MainViewModel vm,
            Func<string?, GerberData?> getGerberData,
            bool includeDefaultCopper = false,
            bool includeCopperShapes  = true,
            bool includeAntennas      = true,
            bool includeVias          = true,
            AnalysisType analysisType = AnalysisType.S11Only)
        {
            Directory.CreateDirectory(outputDir);

            var scriptsDir  = Path.Combine(outputDir, "scripts");
            var geometryDir = Path.Combine(outputDir, "geometry");
            var simDataDir  = Path.Combine(outputDir, "sim_data");
            var resultsDir  = Path.Combine(outputDir, "results");
            Directory.CreateDirectory(scriptsDir);
            Directory.CreateDirectory(geometryDir);
            Directory.CreateDirectory(simDataDir);
            Directory.CreateDirectory(resultsDir);

            var sb = new StringBuilder(16384);
            var stlEntries = new List<(string FileName, string Material, int Priority)>();

            WriteHeader(sb);
            WriteImports(sb);
            WriteSimParameters(sb, vm);
            WriteFdtdSetup(sb, vm);
            WriteMaterials(sb, vm);

            // Geometry
            WriteCarrierGeometry(sb, vm, geometryDir, stlEntries, getGerberData,
                includeDefaultCopper, includeCopperShapes, includeAntennas);

            if (vm.HasModule)
                WriteModuleGeometry(sb, vm, geometryDir, stlEntries, getGerberData,
                    includeDefaultCopper, includeCopperShapes, includeAntennas);

            WriteStlImports(sb, stlEntries);

            if (includeVias)
                WriteVias(sb, vm);

            WriteSolderJoints(sb, vm);

            WritePorts(sb, vm);
            WriteMesh(sb, vm);

            bool needNF2FF = analysisType == AnalysisType.FarField || analysisType == AnalysisType.Both;
            var fd = vm.SimSettings.FieldDumps;
            int nThreads = vm.SimSettings.Solver.NumThreads;
            if (nThreads <= 0) nThreads = Environment.ProcessorCount;
            WriteFieldDumps(sb, vm, fd);
            WriteRun(sb, needNF2FF, nThreads);

            if (analysisType == AnalysisType.S11Only || analysisType == AnalysisType.Both)
                WritePostProcess(sb, vm);

            if (analysisType == AnalysisType.FarField || analysisType == AnalysisType.Both)
                WriteFarFieldPostProcess(sb, vm);

            if (fd.AnyEnabled)
                WriteFieldDumpPostProcess(sb, vm, fd);

            var scriptPath = Path.Combine(scriptsDir, "run_simulation.py");
            File.WriteAllText(scriptPath, sb.ToString(), new UTF8Encoding(false));
        }

        // ── Script sections ──────────────────────────────────────────────────

        private static void WriteHeader(StringBuilder sb)
        {
            sb.AppendLine("# ============================================================");
            sb.AppendLine("# Auto-generated openEMS simulation script");
            sb.AppendLine("# Generated by AntennaSimulatorApp");
            sb.AppendLine("# ============================================================");
            sb.AppendLine();
        }

        /// <summary>
        /// Returns the user-configured openEMS path from Tools → Options, or null.
        /// </summary>
        private static string? ResolveOpenEmsPath()
        {
            string userPath = AppSettings.Instance.OpenEmsPath;
            if (!string.IsNullOrWhiteSpace(userPath) && Directory.Exists(userPath))
                return Path.GetFullPath(userPath);
            return null;
        }

        private static void WriteImports(StringBuilder sb)
        {
            string? resolvedPath = ResolveOpenEmsPath();

            sb.AppendLine("import os, sys");
            sb.AppendLine("import numpy as np");
            sb.AppendLine();
            sb.AppendLine("post_only = '--post-only' in sys.argv");
            sb.AppendLine();
            sb.AppendLine("# --- Locate openEMS ---");
            sb.AppendLine("script_dir = os.path.dirname(os.path.abspath(__file__))");
            sb.AppendLine("sim_base = os.path.dirname(script_dir)  # Sim/");
            sb.AppendLine("geometry_dir = os.path.join(sim_base, 'geometry')");
            sb.AppendLine("sim_data_dir = os.path.join(sim_base, 'sim_data')");
            sb.AppendLine("results_dir  = os.path.join(sim_base, 'results')");
            sb.AppendLine();

            if (resolvedPath != null)
            {
                sb.AppendLine($"openems_path = r'{resolvedPath}'");
            }
            else
            {
                sb.AppendLine("openems_path = None");
                sb.AppendLine("print('WARNING: openEMS path not configured. Please set it in Tools -> Options.')");
            }

            sb.AppendLine("if openems_path and os.path.isdir(openems_path):");
            sb.AppendLine("    os.add_dll_directory(openems_path)");
            sb.AppendLine("    print(f'openEMS found: {openems_path}')");
            sb.AppendLine("else:");
            sb.AppendLine("    print('WARNING: openEMS folder not found, relying on system PATH')");
            sb.AppendLine();
            sb.AppendLine("from CSXCAD import ContinuousStructure");
            sb.AppendLine("from openEMS import openEMS");
            sb.AppendLine("from openEMS.physical_constants import *");
            sb.AppendLine();
        }

        private static void WriteSimParameters(StringBuilder sb, MainViewModel vm)
        {
            var sw = vm.SimSettings.Sweep;
            double fStartHz = sw.StartGHz * 1e9;
            double fStopHz  = sw.StopGHz  * 1e9;
            double f0Hz     = (fStartHz + fStopHz) / 2.0;

            sb.AppendLine("# --- Simulation Parameters ---");
            sb.AppendLine("unit = 1e-3  # all coordinates in mm");
            sb.AppendLine($"f_start = {F(fStartHz)}");
            sb.AppendLine($"f_stop  = {F(fStopHz)}");
            sb.AppendLine($"f0      = {F(f0Hz)}");
            sb.AppendLine();
        }

        private static void WriteFdtdSetup(StringBuilder sb, MainViewModel vm)
        {
            sb.AppendLine("# --- FDTD Setup ---");
            sb.AppendLine($"sim = openEMS(NrTS={vm.SimSettings.Solver.MaxTimesteps}, EndCriteria={F(vm.SimSettings.Solver.EndCriteria)})");
            sb.AppendLine("sim.SetGaussExcite(f0, (f_stop - f_start) / 2)");

            var bc = vm.SimSettings.Boundary;
            // Both PML and OpenAddSpace use PML absorption; OpenAddSpace just adds air padding first
            int pmlN = bc.PmlLayers;
            string bcType = $"'PML_{pmlN}'";

            string Bc(SymmetryType sym) => sym switch
            {
                SymmetryType.PEC => "'PEC'",
                SymmetryType.PMC => "'PMC'",
                _               => bcType
            };

            sb.AppendLine($"sim.SetBoundaryCond([{Bc(bc.SymmetryX)}, {bcType}, " +
                          $"{Bc(bc.SymmetryY)}, {bcType}, {Bc(bc.SymmetryZ)}, {bcType}])");
            sb.AppendLine();
            sb.AppendLine("csx = ContinuousStructure()");
            sb.AppendLine("mesh = csx.GetGrid()");
            sb.AppendLine("mesh.SetDeltaUnit(unit)");
            sb.AppendLine();
        }

        private static void WriteMaterials(StringBuilder sb, MainViewModel vm)
        {
            sb.AppendLine("# --- Materials ---");
            sb.AppendLine("copper = csx.AddMetal('Copper')");

            // Collect unique dielectric materials across both boards
            var mats = new Dictionary<string, (double Eps, double Kappa)>();
            CollectDielectrics(vm.CarrierBoard.Stackup, mats);
            if (vm.HasModule)
                CollectDielectrics(vm.Module.Stackup, mats);

            foreach (var kv in mats)
            {
                sb.AppendLine($"{kv.Key} = csx.AddMaterial('{kv.Key}', " +
                    $"epsilon={F(kv.Value.Eps)}, kappa={F(kv.Value.Kappa)})");
            }
            sb.AppendLine();
        }

        // ── Carrier geometry ─────────────────────────────────────────────────

        private static void WriteCarrierGeometry(
            StringBuilder sb, MainViewModel vm,
            string stlDir, List<(string, string, int)> stlEntries,
            Func<string?, GerberData?> getGerberData,
            bool includeDefaultCopper, bool includeCopperShapes, bool includeAntennas)
        {
            sb.AppendLine("# --- Carrier Board Geometry ---");
            var board = vm.CarrierBoard;
            double xMin = -board.Height / 2.0;
            double xMax =  board.Height / 2.0;
            double yMin = -board.Width;
            double yMax =  0;

            bool pec = vm.SimSettings.Mesh.UsePecSheets;

            // Build effective layer list: skip copper layers that have no content
            // and merge adjacent dielectric layers when the copper between them is empty.
            var layers = board.Stackup.Layers;
            double zFace = 0.0;
            double pendingDielectricThickness = 0;
            string? pendingMatVar = null;
            double pendingZTop = 0;

            foreach (var layer in layers)
            {
                if (layer.Thickness <= 0) continue;

                if (layer.IsConductive)
                {
                    bool hasContent = CopperLayerHasContent(layer, vm, isCarrier: true);

                    if (hasContent)
                    {
                        // Flush pending dielectric before this copper layer
                        if (pendingDielectricThickness > 0 && pendingMatVar != null)
                        {
                            double dBot = pendingZTop - pendingDielectricThickness;
                            sb.AppendLine($"{pendingMatVar}.AddBox(" +
                                $"[{F(xMin)}, {F(yMin)}, {F(dBot)}], " +
                                $"[{F(xMax)}, {F(yMax)}, {F(pendingZTop)}], priority=0)");
                            pendingDielectricThickness = 0;
                            pendingMatVar = null;
                        }

                        double effectiveThickness = pec ? 0 : layer.Thickness;
                        double zBot = zFace - effectiveThickness;

                        if (layer.HasGerber)
                        {
                            ExportGerberLayerStl(stlDir, stlEntries, getGerberData,
                                layer, zFace, $"carrier_gerber_{layer.Name}");
                        }

                        zFace -= effectiveThickness;
                    }
                    else
                    {
                        // No content — skip this copper layer entirely (PEC or not).
                        // Its thickness becomes part of the adjacent dielectric.
                        if (!pec)
                        {
                            // When not using PEC, the physical copper thickness is
                            // absorbed into the surrounding dielectric (minor approx).
                            pendingDielectricThickness += layer.Thickness;
                        }
                        // When PEC, copper thickness is 0 anyway — nothing to add.
                    }
                }
                else
                {
                    // Dielectric layer — accumulate
                    if (pendingDielectricThickness == 0)
                    {
                        pendingZTop = zFace;
                        pendingMatVar = MaterialVarName(layer);
                    }
                    pendingDielectricThickness += layer.Thickness;
                    zFace -= layer.Thickness;
                }
            }

            // Flush remaining dielectric
            if (pendingDielectricThickness > 0 && pendingMatVar != null)
            {
                double dBot = pendingZTop - pendingDielectricThickness;
                sb.AppendLine($"{pendingMatVar}.AddBox(" +
                    $"[{F(xMin)}, {F(yMin)}, {F(dBot)}], " +
                    $"[{F(xMax)}, {F(yMax)}, {F(pendingZTop)}], priority=0)");
            }
            sb.AppendLine();

            // Copper shapes & antenna traces on carrier
            WriteShapePolygons(sb, vm,
                isCarrier: true, board.Stackup,
                includeCopperShapes, includeAntennas);
        }

        // ── Module geometry ──────────────────────────────────────────────────

        private static void WriteModuleGeometry(
            StringBuilder sb, MainViewModel vm,
            string stlDir, List<(string, string, int)> stlEntries,
            Func<string?, GerberData?> getGerberData,
            bool includeDefaultCopper, bool includeCopperShapes, bool includeAntennas)
        {
            sb.AppendLine("# --- RF Module Geometry ---");
            var mod = vm.Module;

            double xMin = mod.PositionY - mod.Height / 2.0;
            double xMax = mod.PositionY + mod.Height / 2.0;
            double yMin = -mod.PositionX - mod.Width;
            double yMax = -mod.PositionX;

            bool pec = vm.SimSettings.Mesh.UsePecSheets;

            // Build effective layer list bottom-to-top: skip copper layers without
            // content and merge adjacent dielectric layers.
            double zBase = MountGap;
            double pendingDielectricThickness = 0;
            string? pendingMatVar = null;
            double pendingZBot = 0;

            foreach (var layer in mod.Stackup.Layers.AsEnumerable().Reverse())
            {
                if (layer.Thickness <= 0) continue;

                if (layer.IsConductive)
                {
                    bool hasContent = CopperLayerHasContent(layer, vm, isCarrier: false);

                    if (hasContent)
                    {
                        // Flush pending dielectric before this copper layer
                        if (pendingDielectricThickness > 0 && pendingMatVar != null)
                        {
                            double dTop = pendingZBot + pendingDielectricThickness;
                            sb.AppendLine($"{pendingMatVar}.AddBox(" +
                                $"[{F(xMin)}, {F(yMin)}, {F(pendingZBot)}], " +
                                $"[{F(xMax)}, {F(yMax)}, {F(dTop)}], priority=0)");
                            pendingDielectricThickness = 0;
                            pendingMatVar = null;
                        }

                        double effectiveThickness = pec ? 0 : layer.Thickness;
                        double zTop = zBase + effectiveThickness;

                        if (layer.HasGerber)
                        {
                            ExportGerberLayerStl(stlDir, stlEntries, getGerberData,
                                layer, zTop, $"module_gerber_{layer.Name}");
                        }

                        zBase = zTop;
                    }
                    else
                    {
                        // No content — skip this copper layer.
                        if (!pec)
                            pendingDielectricThickness += layer.Thickness;
                    }
                }
                else
                {
                    // Dielectric layer — accumulate
                    if (pendingDielectricThickness == 0)
                    {
                        pendingZBot = zBase;
                        pendingMatVar = MaterialVarName(layer);
                    }
                    pendingDielectricThickness += layer.Thickness;
                    zBase += layer.Thickness;
                }
            }

            // Flush remaining dielectric
            if (pendingDielectricThickness > 0 && pendingMatVar != null)
            {
                double dTop = pendingZBot + pendingDielectricThickness;
                sb.AppendLine($"{pendingMatVar}.AddBox(" +
                    $"[{F(xMin)}, {F(yMin)}, {F(pendingZBot)}], " +
                    $"[{F(xMax)}, {F(yMax)}, {F(dTop)}], priority=0)");
            }
            sb.AppendLine();

            // Shapes on module
            WriteShapePolygons(sb, vm,
                isCarrier: false, mod.Stackup,
                includeCopperShapes, includeAntennas);
        }

        // ── STL import statements ────────────────────────────────────────────

        private static void WriteStlImports(StringBuilder sb,
            List<(string FileName, string Material, int Priority)> entries)
        {
            if (entries.Count == 0) return;

            sb.AppendLine("# --- Import STL Geometry ---");
            sb.AppendLine("stl_dir = geometry_dir");

            foreach (var (file, mat, pri) in entries)
            {
                sb.AppendLine($"{mat}.AddPolyhedronReader(" +
                    $"os.path.join(stl_dir, '{file}'), priority={pri})");
            }
            sb.AppendLine();
        }

        // ── Vias ─────────────────────────────────────────────────────────────

        private static void WriteVias(StringBuilder sb, MainViewModel vm)
        {
            if (vm.Vias.Count == 0) return;

            sb.AppendLine("# --- Vias ---");
            bool pec = vm.SimSettings.Mesh.UsePecSheets;
            int idx = 0;
            foreach (var via in vm.Vias)
            {
                if (!via.ShowIn3D) continue;

                var stackup = via.IsCarrier
                    ? vm.CarrierBoard.Stackup
                    : vm.Module.Stackup;

                var fromL = stackup.Layers.FirstOrDefault(l => l.Name == via.FromLayer);
                var toL   = stackup.Layers.FirstOrDefault(l => l.Name == via.ToLayer);
                if (fromL == null || toL == null) continue;

                double z1 = ComputeLayerZFace(stackup.Layers, fromL, via.IsCarrier, pec);
                double z2 = ComputeLayerZFace(stackup.Layers, toL,   via.IsCarrier, pec);
                double fromThk = (pec && fromL.IsConductive) ? 0 : fromL.Thickness;
                double toThk   = (pec && toL.IsConductive)   ? 0 : toL.Thickness;
                double zTop = Math.Max(z1, z2);
                double zBot = Math.Min(z1 - fromThk, z2 - toThk);
                double radius = via.DiameterMm / 2.0;

                sb.AppendLine($"copper.AddCylinder(" +
                    $"[{F(via.X)}, {F(via.Y)}, {F(zBot)}], " +
                    $"[{F(via.X)}, {F(via.Y)}, {F(zTop)}], " +
                    $"{F(radius)}, priority=15)");
                idx++;
            }
            sb.AppendLine();
        }

        // ── Solder Joints ────────────────────────────────────────────────────

        private static void WriteSolderJoints(StringBuilder sb, MainViewModel vm)
        {
            if (!vm.HasModule || vm.SolderJoints.Count == 0) return;

            sb.AppendLine("# --- Solder Joints (module bottom → carrier top) ---");

            bool pec = vm.SimSettings.Mesh.UsePecSheets;

            // carrier top layer
            var carrierTopLayer = vm.CarrierBoard.Stackup.Layers.FirstOrDefault(l => l.IsConductive);
            // module bottom layer
            var moduleLayers = vm.Module.Stackup.Layers.ToList();
            var moduleBottomLayer = moduleLayers.LastOrDefault(l => l.IsConductive);
            if (carrierTopLayer == null || moduleBottomLayer == null) return;

            double zCarrierTop = ComputeLayerZFace(vm.CarrierBoard.Stackup.Layers, carrierTopLayer, true, pec);
            double carrierThk  = (pec && carrierTopLayer.IsConductive) ? 0 : carrierTopLayer.Thickness;
            double zCarrierBot = zCarrierTop - carrierThk;
            double zModuleBot  = ComputeLayerZFace(vm.Module.Stackup.Layers, moduleBottomLayer, false, pec);

            foreach (var sj in vm.SolderJoints)
            {
                if (!sj.ShowIn3D) continue;
                double radius = sj.DiameterMm / 2.0;

                sb.AppendLine($"copper.AddCylinder(" +
                    $"[{F(sj.X)}, {F(sj.Y)}, {F(zCarrierBot)}], " +
                    $"[{F(sj.X)}, {F(sj.Y)}, {F(zModuleBot)}], " +
                    $"{F(radius)}, priority=15)");
            }
            sb.AppendLine();
        }

        // ── Ports ────────────────────────────────────────────────────────────

        private static void WritePorts(StringBuilder sb, MainViewModel vm)
        {
            if (vm.SimSettings.Ports.Count == 0) return;

            sb.AppendLine("# --- Ports ---");
            sb.AppendLine("from openEMS.ports import LumpedPort");
            sb.AppendLine("ports = []");

            for (int i = 0; i < vm.SimSettings.Ports.Count; i++)
            {
                var port = vm.SimSettings.Ports[i];

                // Strip board prefix ("Carrier – ", "Module – ") added by SimSettings UI
                string fromName = StripBoardPrefix(port.FromLayer);
                string toName   = StripBoardPrefix(port.ToLayer);
                bool fromIsModule = port.FromLayer.StartsWith("Module", StringComparison.OrdinalIgnoreCase);
                bool toIsModule   = port.ToLayer.StartsWith("Module", StringComparison.OrdinalIgnoreCase);

                // Resolve layers – use prefix hint, then fallback
                PcbStackup? stackup = null;
                bool isCarrier = true;
                Layer? fromL = null;
                Layer? toL = null;

                if (fromIsModule && vm.HasModule)
                {
                    fromL = vm.Module.Stackup.Layers.FirstOrDefault(l => l.Name == fromName);
                    toL   = vm.Module.Stackup.Layers.FirstOrDefault(l => l.Name == toName);
                    if (fromL != null && toL != null)
                    {
                        stackup = vm.Module.Stackup;
                        isCarrier = false;
                    }
                }

                if (stackup == null)
                {
                    fromL = vm.CarrierBoard.Stackup.Layers.FirstOrDefault(l => l.Name == fromName);
                    toL   = vm.CarrierBoard.Stackup.Layers.FirstOrDefault(l => l.Name == toName);
                    if (fromL != null && toL != null)
                    {
                        stackup = vm.CarrierBoard.Stackup;
                        isCarrier = true;
                    }
                }

                if (stackup == null && vm.HasModule)
                {
                    fromL = vm.Module.Stackup.Layers.FirstOrDefault(l => l.Name == fromName);
                    toL   = vm.Module.Stackup.Layers.FirstOrDefault(l => l.Name == toName);
                    if (fromL != null && toL != null)
                    {
                        stackup = vm.Module.Stackup;
                        isCarrier = false;
                    }
                }

                if (stackup == null || fromL == null || toL == null)
                {
                    sb.AppendLine($"# Port {i + 1} skipped – layers not found");
                    continue;
                }

                // Z faces of each copper layer
                bool pec = vm.SimSettings.Mesh.UsePecSheets;
                double zFromTop = ComputeLayerZFace(stackup.Layers, fromL, isCarrier, pec);
                double fromThk  = (pec && fromL.IsConductive) ? 0 : fromL.Thickness;
                double zFromBot = zFromTop - fromThk;
                double zToTop   = ComputeLayerZFace(stackup.Layers, toL,   isCarrier, pec);
                double toThk    = (pec && toL.IsConductive)   ? 0 : toL.Thickness;
                double zToBot   = zToTop - toThk;

                int direction;
                switch (port.IntegLine)
                {
                    case IntegLine.XPlus: case IntegLine.XMinus:
                        direction = 0; break;
                    case IntegLine.YPlus: case IntegLine.YMinus:
                        direction = 1; break;
                    default:
                        direction = 2; break;
                }

                double hwx = port.WidthX / 2.0;
                double hwy = port.WidthY / 2.0;

                // For Z-directed ports, span only the dielectric gap between
                // the two copper layers (inner faces), so the port does NOT
                // overlap and erase the copper electrodes at each end.
                double zMin, zMax;
                if (direction == 2)
                {
                    // Use inner copper faces: the face of each layer closest
                    // to the other layer.
                    if (zFromTop >= zToTop)
                    {
                        // From-layer is above To-layer
                        zMin = zToTop;    // top face of lower copper = inner face
                        zMax = zFromBot;  // bottom face of upper copper = inner face
                    }
                    else
                    {
                        zMin = zFromTop;
                        zMax = zToBot;
                    }
                }
                else
                {
                    // Non-Z ports: use full extent
                    zMin = Math.Min(Math.Min(zFromBot, zFromTop), Math.Min(zToBot, zToTop));
                    zMax = Math.Max(Math.Max(zFromBot, zFromTop), Math.Max(zToBot, zToTop));
                }

                sb.AppendLine($"ports.append(LumpedPort(csx, {i + 1}, {F(port.Impedance)}, " +
                    $"[{F(port.X - hwx)}, {F(port.Y - hwy)}, {F(zMin)}], " +
                    $"[{F(port.X + hwx)}, {F(port.Y + hwy)}, {F(zMax)}], " +
                    $"{direction}, 1.0, priority=50))");
            }
            sb.AppendLine();
        }

        /// <summary>
        /// Strip "Carrier – " or "Module – " prefix from a layer name
        /// stored by the SimSettings UI.
        /// </summary>
        private static string StripBoardPrefix(string layerName)
        {
            if (string.IsNullOrEmpty(layerName)) return layerName;
            // UI uses en-dash (–) or regular dash (-)
            foreach (var prefix in new[] { "Carrier – ", "Carrier - ", "Module – ", "Module - " })
            {
                if (layerName.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                    return layerName.Substring(prefix.Length);
            }
            return layerName;
        }

        // ── Mesh ─────────────────────────────────────────────────────────────

        private static void WriteMesh(StringBuilder sb, MainViewModel vm)
        {
            var ms = vm.SimSettings.Mesh;
            var bc = vm.SimSettings.Boundary;
            var board = vm.CarrierBoard;

            double xMin = -board.Height / 2.0;
            double xMax =  board.Height / 2.0;
            double yMin = -board.Width;
            double yMax =  0;

            // Z extents (account for PEC sheets: copper has zero thickness)
            bool pecZ = ms.UsePecSheets;
            double carrierThickness = board.Stackup.Layers
                .Sum(l => (pecZ && l.IsConductive) ? 0 : l.Thickness);
            double zTop = 0;
            double zBot = -carrierThickness;
            if (vm.HasModule)
            {
                double modThickness = vm.Module.Stackup.Layers
                    .Sum(l => (pecZ && l.IsConductive) ? 0 : l.Thickness);
                zTop = MountGap + modThickness;
            }

            // Simulation domain extents
            double domXMin, domXMax, domYMin, domYMax, domZMin, domZMax;

            if (bc.ManualSimArea)
            {
                // User-specified exact boundaries
                domXMin = bc.SimXMin; domXMax = bc.SimXMax;
                domYMin = bc.SimYMin; domYMax = bc.SimYMax;
                domZMin = bc.SimZMin; domZMax = bc.SimZMax;
            }
            else
            {
                // Auto-compute: board bounding box + padding
                bool isOpenAdd = bc.Type == BoundaryType.OpenAddSpace;
                double padXp = isOpenAdd ? bc.SpacingXPlus  : 30;
                double padXm = isOpenAdd ? bc.SpacingXMinus : 30;
                double padYp = isOpenAdd ? bc.SpacingYPlus  : 30;
                double padYm = isOpenAdd ? bc.SpacingYMinus : 30;
                double padZp = isOpenAdd ? bc.SpacingZPlus  : 30;
                double padZm = isOpenAdd ? bc.SpacingZMinus : 30;

                domXMin = xMin - padXm; domXMax = xMax + padXp;
                domYMin = yMin - padYm; domYMax = yMax + padYp;
                domZMin = zBot - padZm; domZMax = zTop + padZp;
            }

            sb.AppendLine("# --- Mesh ---");

            // X mesh
            sb.AppendLine($"mesh.AddLine('x', [{F(domXMin)}, {F(xMin)}, {F(xMax)}, {F(domXMax)}])");

            // Y mesh
            sb.AppendLine($"mesh.AddLine('y', [{F(domYMin)}, {F(yMin)}, {F(yMax)}, {F(domYMax)}])");

            // Z mesh – add lines only at merged dielectric slab boundaries.
            // Empty copper layers are skipped; adjacent dielectrics merge into
            // one slab, producing fewer Z seed lines and a bigger timestep.
            sb.Append("mesh.AddLine('z', [");
            sb.Append($"{F(domZMin)}, ");
            {
                bool pec = ms.UsePecSheets;
                var zLines = new List<double>();

                // Carrier (top-down, z decreasing) – mirror WriteCarrierGeometry logic
                double z = 0;
                zLines.Add(z);
                bool carrierPending = false;
                foreach (var layer in board.Stackup.Layers)
                {
                    if (layer.Thickness <= 0) continue;
                    if (layer.IsConductive)
                    {
                        bool hasContent = CopperLayerHasContent(layer, vm, isCarrier: true);
                        if (hasContent)
                        {
                            // Flush: the accumulated dielectric slab ends here
                            if (carrierPending) { zLines.Add(z); carrierPending = false; }
                            double t = pec ? 0 : layer.Thickness;
                            z -= t;
                            zLines.Add(z);
                        }
                        else
                        {
                            // Empty copper – absorbed into surrounding dielectric
                            if (!pec) z -= layer.Thickness;
                        }
                    }
                    else
                    {
                        // Dielectric – just move z, mark pending
                        z -= layer.Thickness;
                        carrierPending = true;
                    }
                }
                if (carrierPending) zLines.Add(z);

                // Module (bottom-up, z increasing) – mirror WriteModuleGeometry logic
                if (vm.HasModule)
                {
                    double zBase = MountGap;
                    zLines.Add(zBase);
                    bool modPending = false;
                    foreach (var layer in vm.Module.Stackup.Layers.Reverse())
                    {
                        if (layer.Thickness <= 0) continue;
                        if (layer.IsConductive)
                        {
                            bool hasContent = CopperLayerHasContent(layer, vm, isCarrier: false);
                            if (hasContent)
                            {
                                if (modPending) { zLines.Add(zBase); modPending = false; }
                                double t = pec ? 0 : layer.Thickness;
                                zBase += t;
                                zLines.Add(zBase);
                            }
                            else
                            {
                                if (!pec) zBase += layer.Thickness;
                            }
                        }
                        else
                        {
                            zBase += layer.Thickness;
                            modPending = true;
                        }
                    }
                    if (modPending) zLines.Add(zBase);
                }

                sb.Append(string.Join(", ", zLines.Distinct().OrderBy(v => v).Select(F)));
            }
            sb.AppendLine($", {F(domZMax)}])");

            // Module boundary mesh lines
            if (vm.HasModule)
            {
                var mod = vm.Module;
                double modXMin = mod.PositionY - mod.Height / 2.0;
                double modXMax = mod.PositionY + mod.Height / 2.0;
                double modYMin = -mod.PositionX - mod.Width;
                double modYMax = -mod.PositionX;
                sb.AppendLine($"mesh.AddLine('x', [{F(modXMin)}, {F(modXMax)}])");
                sb.AppendLine($"mesh.AddLine('y', [{F(modYMin)}, {F(modYMax)}])");
            }

            // Add port box edges to mesh (openEMS snaps port to nearest mesh lines)
            foreach (var port in vm.SimSettings.Ports)
            {
                double hwx = port.WidthX / 2.0;
                double hwy = port.WidthY / 2.0;
                sb.AppendLine($"mesh.AddLine('x', [{F(port.X - hwx)}, {F(port.X)}, {F(port.X + hwx)}])");
                sb.AppendLine($"mesh.AddLine('y', [{F(port.Y - hwy)}, {F(port.Y)}, {F(port.Y + hwy)}])");
            }

            // Add via locations to mesh
            foreach (var via in vm.Vias)
            {
                if (!via.ShowIn3D) continue;
                sb.AppendLine($"mesh.AddLine('x', [{F(via.X)}])");
                sb.AppendLine($"mesh.AddLine('y', [{F(via.Y)}])");
            }

            // Add copper shape / antenna polygon edges to mesh so fine traces
            // are properly resolved by the FDTD grid.
            var shapeXs = new SortedSet<double>();
            var shapeYs = new SortedSet<double>();
            foreach (var shape in vm.ManualShapes)
            {
                if (!shape.ShowIn3D) continue;
                CollectPolyEdges(shape.Vertices, shapeXs, shapeYs);
                foreach (var poly in shape.MergedPolygons)
                    CollectPolyEdges(poly, shapeXs, shapeYs);
            }

            // Refine mesh between polygon edges: when the gap between adjacent
            // seed lines is large relative to the smallest feature, add
            // intermediate lines so FDTD properly resolves inter-trace coupling
            // (critical for meander antennas).
            AddMidpointRefinement(shapeXs, ms.MinStepMm);
            AddMidpointRefinement(shapeYs, ms.MinStepMm);

            // Ensure narrow gaps (trace widths) have at least N cells across.
            if (ms.MinCellsPerTrace >= 2)
            {
                double xyMaxRes = 3e8 / (ms.MeshFreqGHz * 1e9) * 1e3 / Math.Max(ms.CellsPerWavelength, 1);
                SubdivideNarrowGaps(shapeXs, ms.MinCellsPerTrace, maxRes: xyMaxRes, minCellSize: ms.MinStepMm);
                SubdivideNarrowGaps(shapeYs, ms.MinCellsPerTrace, maxRes: xyMaxRes, minCellSize: ms.MinStepMm);
            }

            // Final guarantee: remove any lines that are closer than MinStepMm.
            EnforceMinStep(shapeXs, ms.MinStepMm);
            EnforceMinStep(shapeYs, ms.MinStepMm);

            if (shapeXs.Count > 0)
                sb.AppendLine($"mesh.AddLine('x', [{string.Join(", ", shapeXs.Select(F))}])");
            if (shapeYs.Count > 0)
                sb.AppendLine($"mesh.AddLine('y', [{string.Join(", ", shapeYs.Select(F))}])");

            // Smooth mesh
            double maxRes = ms.CellsPerWavelength > 0
                ? 3e8 / (ms.MeshFreqGHz * 1e9) * 1e3 / ms.CellsPerWavelength
                : 1.0;
            sb.AppendLine();
            sb.AppendLine($"mesh.SmoothMeshLines('x', {F(maxRes)}, ratio=1.5)");
            sb.AppendLine($"mesh.SmoothMeshLines('y', {F(maxRes)}, ratio=1.5)");
            sb.AppendLine($"mesh.SmoothMeshLines('z', {F(Math.Min(maxRes, ms.ZMaxStepMm))}, ratio=1.4)");
            sb.AppendLine();
        }

        // ── Field dumps ──────────────────────────────────────────────────────

        /// <summary>
        /// Add frequency-domain field dumps (J / E / H) at the center frequency.
        /// The dumps are 2D XY slices on the antenna copper-layer surface.
        /// </summary>
        private static void WriteFieldDumps(StringBuilder sb, MainViewModel vm, FieldDumpSettings fd)
        {
            if (!fd.AnyEnabled) return;

            var board = vm.CarrierBoard;
            double xMin = -board.Height / 2.0;
            double xMax =  board.Height / 2.0;
            double yMin = -board.Width;
            double yMax =  0;
            // Antenna surface Z (top of TOP copper for carrier, top of module if present)
            bool pecFd = vm.SimSettings.Mesh.UsePecSheets;
            double zSurface;
            if (vm.HasModule)
            {
                double modThk = vm.Module.Stackup.Layers
                    .Sum(l => (pecFd && l.IsConductive) ? 0 : l.Thickness);
                zSurface = MountGap + modThk;
            }
            else
            {
                zSurface = 0;
            }

            sb.AppendLine("# --- Field Dumps (frequency domain, 2-D XY slice) ---");
            sb.AppendLine($"_fd_f0 = f0  # dump frequency");
            sb.AppendLine();

            if (fd.EnableSurfaceCurrent)
            {
                // dump_type=12 → current density (freq domain), dump_mode=2 → cell interpolated
                sb.AppendLine("Jf_dump = csx.AddDump('Jf_surface', dump_type=12, dump_mode=2, file_type=1)");
                sb.AppendLine("Jf_dump.SetFrequency(_fd_f0)");
                sb.AppendLine($"Jf_dump.AddBox([{F(xMin)}, {F(yMin)}, {F(zSurface)}], [{F(xMax)}, {F(yMax)}, {F(zSurface)}])");
                sb.AppendLine();
            }
            if (fd.EnableEField)
            {
                // dump_type=10 → E-field (freq domain)
                sb.AppendLine("Ef_dump = csx.AddDump('Ef_surface', dump_type=10, dump_mode=2, file_type=1)");
                sb.AppendLine("Ef_dump.SetFrequency(_fd_f0)");
                sb.AppendLine($"Ef_dump.AddBox([{F(xMin)}, {F(yMin)}, {F(zSurface)}], [{F(xMax)}, {F(yMax)}, {F(zSurface)}])");
                sb.AppendLine();
            }
            if (fd.EnableHField)
            {
                // dump_type=11 → H-field (freq domain)
                sb.AppendLine("Hf_dump = csx.AddDump('Hf_surface', dump_type=11, dump_mode=2, file_type=1)");
                sb.AppendLine("Hf_dump.SetFrequency(_fd_f0)");
                sb.AppendLine($"Hf_dump.AddBox([{F(xMin)}, {F(yMin)}, {F(zSurface)}], [{F(xMax)}, {F(yMax)}, {F(zSurface)}])");
                sb.AppendLine();
            }
        }

        // ── Run & post-process ───────────────────────────────────────────────

        private static void WriteRun(StringBuilder sb, bool includeNF2FF, int numThreads)
        {
            sb.AppendLine("# --- Run Simulation ---");
            sb.AppendLine("sim_path = sim_data_dir");
            sb.AppendLine("os.makedirs(sim_path, exist_ok=True)");
            sb.AppendLine("csx.Write2XML(os.path.join(sim_path, 'antenna.xml'))");
            sb.AppendLine("sim.SetCSX(csx)");
            sb.AppendLine();

            if (includeNF2FF)
            {
                sb.AppendLine("# --- NF2FF Recording Box ---");
                sb.AppendLine("from openEMS.nf2ff import nf2ff");
                sb.AppendLine("nf2ff_box = sim.CreateNF2FFBox()");
                sb.AppendLine();
            }

            sb.AppendLine("if not post_only:");
            sb.AppendLine("    print('Starting openEMS simulation...')");
            sb.AppendLine($"    sim.Run(sim_path, verbose=2, numThreads={numThreads})");
            sb.AppendLine("else:");
            sb.AppendLine("    print('Post-processing only (--post-only mode)')");
            sb.AppendLine();
        }

        private static void WritePostProcess(StringBuilder sb, MainViewModel vm)
        {
            if (vm.SimSettings.Ports.Count == 0) return;

            var sw = vm.SimSettings.Sweep;
            double fStartHz = sw.StartGHz * 1e9;
            double fStopHz  = sw.StopGHz  * 1e9;

            sb.AppendLine("# --- Post-Processing: S11 ---");
            sb.AppendLine($"freq = np.linspace({F(fStartHz)}, {F(fStopHz)}, {sw.NumPoints})");
            sb.AppendLine("try:");
            sb.AppendLine("    for p in ports:");
            sb.AppendLine("        p.CalcPort(sim_path, freq)");
            sb.AppendLine("except Exception as e:");
            sb.AppendLine("    print(f'[WARN] Port data not ready yet: {e}')");
            sb.AppendLine("    sys.exit(0)");
            sb.AppendLine();
            sb.AppendLine("if len(ports) == 0:");
            sb.AppendLine("    print('[ERROR] No ports defined – cannot compute S11.')");
            sb.AppendLine("    sys.exit(1)");
            sb.AppendLine();
            sb.AppendLine("s11_dB = 20 * np.log10(np.abs(ports[0].uf_ref / ports[0].uf_inc))");
            sb.AppendLine("s11_complex = ports[0].uf_ref / ports[0].uf_inc");
            sb.AppendLine("idx_min = np.argmin(s11_dB)");
            sb.AppendLine("print(f'Resonance: {freq[idx_min]/1e9:.4f} GHz,  S11 = {s11_dB[idx_min]:.2f} dB')");
            sb.AppendLine();

            // Save S11 data as CSV (dB + complex for VSWR/impedance/Smith)
            sb.AppendLine("# --- Save S11 CSV ---");
            sb.AppendLine("csv_path = os.path.join(results_dir, 'S11.csv')");
            sb.AppendLine("np.savetxt(csv_path, np.column_stack((freq / 1e9, s11_dB, np.real(s11_complex), np.imag(s11_complex))),");
            sb.AppendLine("           delimiter=',', header='Frequency_GHz,S11_dB,S11_Real,S11_Imag', comments='')");
            sb.AppendLine("print(f'S11 data saved to {csv_path}')");
            sb.AppendLine();

            // Save S11 plot
            sb.AppendLine("try:");
            sb.AppendLine("    import matplotlib");
            sb.AppendLine("    matplotlib.use('Agg')");
            sb.AppendLine("    import matplotlib.pyplot as plt");
            sb.AppendLine("    fig, ax = plt.subplots()");
            sb.AppendLine("    ax.plot(freq / 1e9, s11_dB, 'b-', linewidth=1.5)");
            sb.AppendLine("    ax.set_xlabel('Frequency (GHz)')");
            sb.AppendLine("    ax.set_ylabel('S11 (dB)')");
            sb.AppendLine("    ax.set_title('Return Loss')");
            sb.AppendLine("    ax.grid(True)");
            sb.AppendLine("    ax.axhline(-10, color='r', linestyle='--', alpha=0.5, label='-10 dB')");
            sb.AppendLine("    ax.legend()");
            sb.AppendLine("    plot_path = os.path.join(results_dir, 'S11.png')");
            sb.AppendLine("    fig.savefig(plot_path, dpi=150)");
            sb.AppendLine("    plt.close(fig)");
            sb.AppendLine("    print(f'S11 plot saved to {plot_path}')");
            sb.AppendLine("except ImportError:");
            sb.AppendLine("    print('matplotlib not available - skipping plot.')");
            sb.AppendLine();
        }

        // ── NF2FF (Near-Field to Far-Field) ──────────────────────────────────

        private static void WriteFarFieldPostProcess(StringBuilder sb, MainViewModel vm)
        {
            if (vm.SimSettings.Ports.Count == 0) return;

            var sw = vm.SimSettings.Sweep;
            double fStartHz = sw.StartGHz * 1e9;
            double fStopHz  = sw.StopGHz  * 1e9;
            double f0Hz     = (fStartHz + fStopHz) / 2.0;

            sb.AppendLine("# --- Post-Processing: Far-Field ---");
            sb.AppendLine($"ff_freq = np.linspace({F(fStartHz)}, {F(fStopHz)}, {sw.NumPoints})");
            sb.AppendLine();

            // Calculate port data if not already done (for FarField-only mode)
            sb.AppendLine("try:");
            sb.AppendLine("    _ = ports[0].uf_inc");
            sb.AppendLine("except:");
            sb.AppendLine("    try:");
            sb.AppendLine($"        for p in ports:");
            sb.AppendLine($"            p.CalcPort(sim_path, ff_freq)");
            sb.AppendLine("    except Exception as e:");
            sb.AppendLine("        print(f'[WARN] Port data not ready yet: {e}')");
            sb.AppendLine("        sys.exit(0)");
            sb.AppendLine();

            // Find resonant frequency from S11
            sb.AppendLine("ff_s11_dB = 20 * np.log10(np.abs(ports[0].uf_ref / ports[0].uf_inc))");
            sb.AppendLine("ff_idx_min = np.argmin(ff_s11_dB)");
            sb.AppendLine("f_res = ff_freq[ff_idx_min]");
            sb.AppendLine("print(f'Far-field at resonance: {f_res/1e9:.4f} GHz')");
            sb.AppendLine();

            // Compute NF2FF at resonance frequency
            sb.AppendLine("theta = np.arange(-180, 180.5, 1)");
            sb.AppendLine("phi_E = 0    # E-plane (XZ)");
            sb.AppendLine("phi_H = 90   # H-plane (YZ)");
            sb.AppendLine();

            // Accepted power for realized gain
            sb.AppendLine("P_in = 0.5 * np.real(ports[0].uf_tot[ff_idx_min] * np.conj(ports[0].if_tot[ff_idx_min]))");
            sb.AppendLine();

            // E-plane cut
            sb.AppendLine("nf2ff_res_E = nf2ff_box.CalcNF2FF(sim_path, f_res, theta, phi_E, center=[0,0,0])");
            sb.AppendLine("E_norm = nf2ff_res_E.E_norm[0]");
            sb.AppendLine("Dmax_E = nf2ff_res_E.Dmax[0]");
            sb.AppendLine();

            // H-plane cut
            sb.AppendLine("nf2ff_res_H = nf2ff_box.CalcNF2FF(sim_path, f_res, theta, phi_H, center=[0,0,0])");
            sb.AppendLine("H_norm = nf2ff_res_H.E_norm[0]");
            sb.AppendLine("Dmax_H = nf2ff_res_H.Dmax[0]");
            sb.AppendLine();

            // Compute directivity in dBi
            sb.AppendLine("D_E_dBi = 10 * np.log10(nf2ff_res_E.Dmax[0])");
            sb.AppendLine("D_H_dBi = 10 * np.log10(nf2ff_res_H.Dmax[0])");
            sb.AppendLine();

            // Realized gain using accepted power
            sb.AppendLine("if P_in > 0:");
            sb.AppendLine("    realized_gain_E = (E_norm**2 / np.max(E_norm**2)) * nf2ff_res_E.Dmax[0]");
            sb.AppendLine("    realized_gain_H = (H_norm**2 / np.max(H_norm**2)) * nf2ff_res_H.Dmax[0]");
            sb.AppendLine("else:");
            sb.AppendLine("    realized_gain_E = E_norm**2 / np.max(E_norm**2) if np.max(E_norm**2) > 0 else E_norm * 0");
            sb.AppendLine("    realized_gain_H = H_norm**2 / np.max(H_norm**2) if np.max(H_norm**2) > 0 else H_norm * 0");
            sb.AppendLine();

            // Normalized pattern in dB
            sb.AppendLine("E_pattern_dB = 10 * np.log10(E_norm**2 / np.max(E_norm**2) + 1e-12)");
            sb.AppendLine("H_pattern_dB = 10 * np.log10(H_norm**2 / np.max(H_norm**2) + 1e-12)");
            sb.AppendLine();

            // Radiation efficiency
            sb.AppendLine("Prad = nf2ff_res_E.Prad[0]");
            sb.AppendLine("eff = Prad / P_in if P_in > 0 else 0");
            sb.AppendLine("print(f'Directivity: {D_E_dBi:.2f} dBi,  Radiation Efficiency: {eff*100:.1f}%')");
            sb.AppendLine();

            // Save E-plane CSV: Theta, E_pattern_dB
            sb.AppendLine("eplane_csv = os.path.join(results_dir, 'FarField_Eplane.csv')");
            sb.AppendLine("np.savetxt(eplane_csv, np.column_stack((theta, E_pattern_dB)),");
            sb.AppendLine("           delimiter=',', header='Theta_deg,Pattern_dB', comments='')");
            sb.AppendLine("print(f'E-plane pattern saved to {eplane_csv}')");
            sb.AppendLine();

            // Save H-plane CSV: Theta, H_pattern_dB
            sb.AppendLine("hplane_csv = os.path.join(results_dir, 'FarField_Hplane.csv')");
            sb.AppendLine("np.savetxt(hplane_csv, np.column_stack((theta, H_pattern_dB)),");
            sb.AppendLine("           delimiter=',', header='Theta_deg,Pattern_dB', comments='')");
            sb.AppendLine("print(f'H-plane pattern saved to {hplane_csv}')");
            sb.AppendLine();

            // Save summary CSV with key metrics
            sb.AppendLine("summary_csv = os.path.join(results_dir, 'FarField_Summary.csv')");
            sb.AppendLine("with open(summary_csv, 'w') as f:");
            sb.AppendLine("    f.write('Parameter,Value\\n')");
            sb.AppendLine("    f.write(f'Frequency_GHz,{f_res/1e9:.6f}\\n')");
            sb.AppendLine("    f.write(f'Directivity_dBi,{D_E_dBi:.4f}\\n')");
            sb.AppendLine("    f.write(f'RadiationEfficiency,{eff:.6f}\\n')");
            sb.AppendLine("    f.write(f'Prad_W,{Prad:.6e}\\n')");
            sb.AppendLine("    f.write(f'Pin_W,{P_in:.6e}\\n')");
            sb.AppendLine("print(f'Far-field summary saved to {summary_csv}')");
            sb.AppendLine();

            // Save optional matplotlib plots
            sb.AppendLine("try:");
            sb.AppendLine("    import matplotlib");
            sb.AppendLine("    matplotlib.use('Agg')");
            sb.AppendLine("    import matplotlib.pyplot as plt");
            sb.AppendLine();
            sb.AppendLine("    # --- Rectangular pattern plot ---");
            sb.AppendLine("    fig, ax = plt.subplots(figsize=(8, 5))");
            sb.AppendLine("    ax.plot(theta, E_pattern_dB, 'b-', linewidth=1.5, label='E-plane')");
            sb.AppendLine("    ax.plot(theta, H_pattern_dB, 'r--', linewidth=1.5, label='H-plane')");
            sb.AppendLine("    ax.set_xlabel('Theta (degrees)')");
            sb.AppendLine("    ax.set_ylabel('Normalized Pattern (dB)')");
            sb.AppendLine("    ax.set_title(f'Far-Field Pattern @ {f_res/1e9:.3f} GHz')");
            sb.AppendLine("    ax.set_ylim([-40, 5])");
            sb.AppendLine("    ax.grid(True)");
            sb.AppendLine("    ax.legend()");
            sb.AppendLine("    fig.savefig(os.path.join(results_dir, 'FarField_Rectangular.png'), dpi=150)");
            sb.AppendLine("    plt.close(fig)");
            sb.AppendLine();
            sb.AppendLine("    # --- Polar pattern plot ---");
            sb.AppendLine("    fig, (ax1, ax2) = plt.subplots(1, 2, subplot_kw={'polar': True}, figsize=(12, 5))");
            sb.AppendLine("    theta_rad = np.deg2rad(theta)");
            sb.AppendLine("    ax1.plot(theta_rad, np.clip(E_pattern_dB, -40, 0) + 40, 'b-', linewidth=1.5)");
            sb.AppendLine("    ax1.set_title('E-plane', pad=15)");
            sb.AppendLine("    ax1.set_ylim([0, 40])");
            sb.AppendLine("    ax2.plot(theta_rad, np.clip(H_pattern_dB, -40, 0) + 40, 'r-', linewidth=1.5)");
            sb.AppendLine("    ax2.set_title('H-plane', pad=15)");
            sb.AppendLine("    ax2.set_ylim([0, 40])");
            sb.AppendLine("    fig.savefig(os.path.join(results_dir, 'FarField_Polar.png'), dpi=150)");
            sb.AppendLine("    plt.close(fig)");
            sb.AppendLine("    print('Far-field pattern plots saved.')");
            sb.AppendLine("except ImportError:");
            sb.AppendLine("    print('matplotlib not available - skipping far-field plots.')");
            sb.AppendLine();

            // ── Full 3-D pattern (theta × phi sweep) ──
            sb.AppendLine("# --- 3D Far-Field Pattern ---");
            sb.AppendLine("print('Computing full 3D far-field pattern ...')");
            sb.AppendLine("theta_3d = np.arange(0, 181, 5)");
            sb.AppendLine("phi_3d   = np.arange(0, 361, 5)");
            sb.AppendLine("nf2ff_3d = nf2ff_box.CalcNF2FF(sim_path, f_res, theta_3d, phi_3d, center=[0,0,0])");
            sb.AppendLine("E3d = nf2ff_3d.E_norm[0]");
            sb.AppendLine("E3d_max2 = np.max(E3d**2)");
            sb.AppendLine("if E3d_max2 > 0:");
            sb.AppendLine("    E3d_dB = 10 * np.log10(E3d**2 / E3d_max2 + 1e-12)");
            sb.AppendLine("else:");
            sb.AppendLine("    E3d_dB = np.zeros_like(E3d)");
            sb.AppendLine("ff3d_csv = os.path.join(results_dir, 'FarField_3D.csv')");
            sb.AppendLine("with open(ff3d_csv, 'w') as f3d:");
            sb.AppendLine("    f3d.write('Theta_deg,Phi_deg,Pattern_dB\\n')");
            sb.AppendLine("    for ti in range(len(theta_3d)):");
            sb.AppendLine("        for pi in range(len(phi_3d)):");
            sb.AppendLine("            f3d.write(f'{theta_3d[ti]:.1f},{phi_3d[pi]:.1f},{E3d_dB[ti,pi]:.4f}\\n')");
            sb.AppendLine("print(f'3D far-field pattern saved to {ff3d_csv}')");
            sb.AppendLine();
        }

        // ── Field dump post-processing ───────────────────────────────────────

        /// <summary>
        /// Generate matplotlib heatmap PNGs from HDF5 field dumps.
        /// Each dump file stores mesh coordinates and complex vector field data.
        /// We compute |F| = sqrt(|Fx|² + |Fy|² + |Fz|²) and plot as 2D heatmap.
        /// </summary>
        private static void WriteShapeOutlineData(StringBuilder sb, MainViewModel vm)
        {
            // Emit Python list entries for all visible copper/antenna shapes on the carrier TOP layer.
            // Coordinates are in mm (the same coordinate system used by the exporter).
            foreach (var shape in vm.ManualShapes)
            {
                if (!shape.IsCarrier || !shape.ShowIn3D) continue;
                if (shape.Vertices == null || shape.Vertices.Count < 3) continue;

                bool isAnt = shape.Name?.StartsWith("Antenna (") == true;
                string isAntStr = isAnt ? "True" : "False";

                // Emit main polygon
                EmitShapeOutlinePoly(sb, shape.Vertices, shape.Name ?? "shape", isAntStr);

                // Emit merged sub-polygons
                foreach (var poly in shape.MergedPolygons)
                {
                    if (poly == null || poly.Count < 3) continue;
                    EmitShapeOutlinePoly(sb, poly, shape.Name ?? "shape", isAntStr);
                }
            }
        }

        private static void EmitShapeOutlinePoly(StringBuilder sb, IList<ShapeVertex> verts, string name, string isAntStr)
        {
            if (verts == null || verts.Count < 3) return;
            var pts = verts.ToList();
            // Build Python list of (x, y) tuples
            var xyPairs = string.Join(", ", pts.Select(p => $"({F(p.X)}, {F(p.Y)})"));
            sb.AppendLine($"    _shape_outlines.append({{'name': '{EscapePy(name)}', 'is_antenna': {isAntStr}, 'xy': [{xyPairs}]}})");
        }

        private static string EscapePy(string s) => s.Replace("\\", "\\\\").Replace("'", "\\'");

        private static void WriteFieldDumpPostProcess(StringBuilder sb, MainViewModel vm, FieldDumpSettings fd)
        {
            sb.AppendLine("# --- Post-Processing: Field Dump Heatmaps ---");
            sb.AppendLine("try:");
            sb.AppendLine("    import h5py");
            sb.AppendLine("    import matplotlib");
            sb.AppendLine("    matplotlib.use('Agg')");
            sb.AppendLine("    import matplotlib.pyplot as plt");
            sb.AppendLine("    from matplotlib.colors import LogNorm");
            sb.AppendLine("    from matplotlib.patches import Polygon as MplPoly");
            sb.AppendLine("except ImportError as _imp_err:");
            sb.AppendLine("    print(f'[WARN] Skipping field plots: {_imp_err}')");
            sb.AppendLine("    h5py = None");
            sb.AppendLine();

            // ── Emit shape outline data as Python lists ──
            // Each entry: { 'name': str, 'is_antenna': bool, 'xy': [(x,y), ...] }
            sb.AppendLine("if h5py is not None:");
            sb.AppendLine("    _shape_outlines = []");
            if (fd.OverlayShapeOutline)
            {
                WriteShapeOutlineData(sb, vm);
            }
            sb.AppendLine();

            sb.AppendLine("    def _plot_field_dump(h5_dir, name, title, cmap='hot'):");
            sb.AppendLine("        \"\"\"Read an openEMS HDF5 field dump and save a heatmap PNG.\"\"\"");
            sb.AppendLine("        h5_path = os.path.join(sim_path, name + '.h5')");
            sb.AppendLine("        if not os.path.isfile(h5_path):");
            sb.AppendLine("            print(f'[WARN] Field dump not found: {h5_path}')");
            sb.AppendLine("            return");
            sb.AppendLine("        try:");
            sb.AppendLine("            with h5py.File(h5_path, 'r') as hf:");
            sb.AppendLine("                x = np.array(hf['/Mesh/x']) * 1e3  # m → mm");
            sb.AppendLine("                y = np.array(hf['/Mesh/y']) * 1e3  # m → mm");
            sb.AppendLine("                fd_grp = hf['/FieldData/FD']");
            sb.AppendLine("                re = np.array(fd_grp['f0_real'])  # (3, Nz, Ny, Nx)");
            sb.AppendLine("                im = np.array(fd_grp['f0_imag'])");
            sb.AppendLine("                mag = np.sqrt(np.sum(re**2 + im**2, axis=0))");
            sb.AppendLine("                mag = np.squeeze(mag)");
            sb.AppendLine("                if mag.ndim == 1:");
            sb.AppendLine("                    print(f'[WARN] {name}: unexpected 1D field data')");
            sb.AppendLine("                    return");
            sb.AppendLine("                vmax = mag.max()");
            sb.AppendLine("                if vmax == 0:");
            sb.AppendLine("                    print(f'[WARN] {name}: all-zero field data')");
            sb.AppendLine("                    return");
            sb.AppendLine("                vmin = max(vmax * 1e-3, mag[mag > 0].min()) if np.any(mag > 0) else 1e-10");
            sb.AppendLine();
            sb.AppendLine("                # --- Determine view bounds: prefer antenna shapes, then field data ---");
            sb.AppendLine("                _ant_shapes = [s for s in _shape_outlines if s['is_antenna']]");
            sb.AppendLine("                _crop_src = _ant_shapes if _ant_shapes else _shape_outlines");
            sb.AppendLine("                if len(_crop_src) > 0:");
            sb.AppendLine("                    all_sx = [px for s in _crop_src for px, _ in s['xy']]");
            sb.AppendLine("                    all_sy = [py for s in _crop_src for _, py in s['xy']]");
            sb.AppendLine("                    margin_mm = 3.0");
            sb.AppendLine("                    x_lo = min(all_sx) - margin_mm");
            sb.AppendLine("                    x_hi = max(all_sx) + margin_mm");
            sb.AppendLine("                    y_lo = min(all_sy) - margin_mm");
            sb.AppendLine("                    y_hi = max(all_sy) + margin_mm");
            sb.AppendLine("                else:");
            sb.AppendLine("                    active = mag >= vmin");
            sb.AppendLine("                    rows = np.where(active.any(axis=1))[0]");
            sb.AppendLine("                    cols = np.where(active.any(axis=0))[0]");
            sb.AppendLine("                    if len(rows) > 0 and len(cols) > 0:");
            sb.AppendLine("                        margin_mm = 5.0");
            sb.AppendLine("                        x_lo = x[max(cols[0]-1, 0)] - margin_mm");
            sb.AppendLine("                        x_hi = x[min(cols[-1]+1, len(x)-1)] + margin_mm");
            sb.AppendLine("                        y_lo = y[max(rows[0]-1, 0)] - margin_mm");
            sb.AppendLine("                        y_hi = y[min(rows[-1]+1, len(y)-1)] + margin_mm");
            sb.AppendLine("                    else:");
            sb.AppendLine("                        x_lo, x_hi = x[0], x[-1]");
            sb.AppendLine("                        y_lo, y_hi = y[0], y[-1]");
            sb.AppendLine();
            sb.AppendLine("                fig, ax = plt.subplots(figsize=(10, 8))");
            sb.AppendLine("                pcm = ax.pcolormesh(x, y, mag, shading='auto', cmap=cmap,");
            sb.AppendLine("                                    norm=LogNorm(vmin=vmin, vmax=vmax))");
            sb.AppendLine("                ax.set_xlim(x_lo, x_hi)");
            sb.AppendLine("                ax.set_ylim(y_lo, y_hi)");
            sb.AppendLine();
            sb.AppendLine("                # --- Overlay shape outlines ---");
            sb.AppendLine("                for shp in _shape_outlines:");
            sb.AppendLine("                    ec = 'lime' if shp['is_antenna'] else 'cyan'");
            sb.AppendLine("                    lw = 1.5 if shp['is_antenna'] else 0.8");
            sb.AppendLine("                    poly = MplPoly(shp['xy'], closed=True, fill=False,");
            sb.AppendLine("                                   edgecolor=ec, linewidth=lw, linestyle='-')");
            sb.AppendLine("                    ax.add_patch(poly)");
            sb.AppendLine();
            sb.AppendLine("                ax.set_xlabel('X (mm)')");
            sb.AppendLine("                ax.set_ylabel('Y (mm)')");
            sb.AppendLine("                ax.set_title(title)");
            sb.AppendLine("                ax.set_aspect('equal')");
            sb.AppendLine("                plt.colorbar(pcm, ax=ax, label='Magnitude')");
            sb.AppendLine("                plt.tight_layout()");
            sb.AppendLine("                png_path = os.path.join(results_dir, name + '.png')");
            sb.AppendLine("                fig.savefig(png_path, dpi=150)");
            sb.AppendLine("                plt.close(fig)");
            sb.AppendLine("                print(f'Field plot saved: {png_path}')");
            // Also save the raw data as CSV for the WPF viewer
            sb.AppendLine("                csv_path = os.path.join(results_dir, name + '.csv')");
            sb.AppendLine("                with open(csv_path, 'w') as csvf:");
            sb.AppendLine("                    csvf.write('# x_coords: ' + ','.join(f'{v:.6g}' for v in x) + '\\n')");
            sb.AppendLine("                    csvf.write('# y_coords: ' + ','.join(f'{v:.6g}' for v in y) + '\\n')");
            sb.AppendLine("                    for row_i in range(mag.shape[0]):");
            sb.AppendLine("                        csvf.write(','.join(f'{v:.6e}' for v in mag[row_i, :]) + '\\n')");
            sb.AppendLine("        except Exception as ex:");
            sb.AppendLine("            print(f'[WARN] Failed to plot {name}: {ex}')");
            sb.AppendLine();

            if (fd.EnableSurfaceCurrent)
            {
                sb.AppendLine("    _plot_field_dump(sim_path, 'Jf_surface', 'Surface Current Density |J| (A/m)', 'hot')");
            }
            if (fd.EnableEField)
            {
                sb.AppendLine("    _plot_field_dump(sim_path, 'Ef_surface', 'Electric Field |E| (V/m)', 'viridis')");
            }
            if (fd.EnableHField)
            {
                sb.AppendLine("    _plot_field_dump(sim_path, 'Hf_surface', 'Magnetic Field |H| (A/m)', 'inferno')");
            }
            sb.AppendLine();
        }

        // ── Helpers: STL export ──────────────────────────────────────────────

        /// <summary>
        /// Write copper shapes as native CSXCAD AddLinPoly calls instead of STL files.
        /// This avoids PolyhedronReader voxelization issues with non-manifold meshes.
        /// </summary>
        private static void WriteShapePolygons(
            StringBuilder sb, MainViewModel vm,
            bool isCarrier, PcbStackup stackup,
            bool includeCopperShapes, bool includeAntennas)
        {
            string boardTag = isCarrier ? "carrier" : "module";
            int idx = 0;

            foreach (var shape in vm.ManualShapes)
            {
                if (shape.IsCarrier != isCarrier || !shape.ShowIn3D) continue;

                bool isAnt = shape.Name?.StartsWith("Antenna (") == true;
                if (isAnt && !includeAntennas) continue;
                if (!isAnt && !includeCopperShapes) continue;

                var targetLayer = stackup.Layers
                    .FirstOrDefault(l => l.Name == shape.LayerName);
                if (targetLayer == null) continue;

                bool pec = vm.SimSettings.Mesh.UsePecSheets;
                double zFace = ComputeLayerZFace(stackup.Layers, targetLayer, isCarrier, pec);
                double effThk = (pec && targetLayer.IsConductive) ? 0 : targetLayer.Thickness;
                double zBase = zFace - effThk;
                double thickness = effThk;
                int priority = isAnt ? 15 : 12;

                // Main polygon
                WriteLinPolyForVertices(sb, shape.Vertices, zBase, thickness, priority,
                    $"{boardTag}_{shape.Name}_main_{idx}");

                // Merged sub-polygons
                int subIdx = 0;
                foreach (var poly in shape.MergedPolygons)
                {
                    WriteLinPolyForVertices(sb, poly, zBase, thickness, priority,
                        $"{boardTag}_{shape.Name}_merged_{idx}_{subIdx}");
                    subIdx++;
                }
                idx++;
            }
        }

        /// <summary>
        /// Emit a single copper.AddLinPoly(...) call for a closed polygon vertex list.
        /// </summary>
        private static void WriteLinPolyForVertices(
            StringBuilder sb, IList<ShapeVertex> verts,
            double zBase, double thickness, int priority, string comment)
        {
            if (verts == null || verts.Count < 3) return;

            // Strip duplicate closing vertex if present
            var pts = verts.ToList();
            while (pts.Count > 3)
            {
                var first = pts[0];
                var last = pts[pts.Count - 1];
                if (Math.Abs(first.X - last.X) < 1e-6 &&
                    Math.Abs(first.Y - last.Y) < 1e-6)
                    pts.RemoveAt(pts.Count - 1);
                else break;
            }
            if (pts.Count < 3) return;

            // Build numpy array string: np.array([[x0,x1,...],[y0,y1,...]])
            var xs = string.Join(", ", pts.Select(p => F(p.X)));
            var ys = string.Join(", ", pts.Select(p => F(p.Y)));

            sb.AppendLine($"# {comment}");
            if (Math.Abs(thickness) < 1e-9)
            {
                // Zero-thickness PEC sheet: use AddPolygon (2D surface)
                // AddLinPoly with thickness=0 is ignored by openEMS.
                sb.AppendLine($"copper.AddPolygon(np.array([[{xs}], [{ys}]]), " +
                    $"'z', {F(zBase)}, priority={priority})");
            }
            else
            {
                sb.AppendLine($"copper.AddLinPoly(np.array([[{xs}], [{ys}]]), " +
                    $"'z', {F(zBase)}, {F(thickness)}, priority={priority})");
            }
        }

        private static void ExportGerberLayerStl(
            string stlDir, List<(string, string, int)> stlEntries,
            Func<string?, GerberData?> getGerberData,
            Layer layer, double zFace, string tag)
        {
            var gd = getGerberData(layer.GerberFilePath);
            if (gd == null) return;

            var meshes = ExtractMeshes(
                GerberParser.BuildMeshes(gd, zFace, layer.Thickness,
                    layer.GerberOffsetX, layer.GerberOffsetY,
                    double.TryParse(layer.GerberRotation, out double rot) ? rot : 0));

            if (meshes.Count == 0) return;

            string stlName = $"{tag}.stl";
            StlExporter.Export(Path.Combine(stlDir, stlName), meshes);
            stlEntries.Add((stlName, "copper", 10));
        }

        private static List<MeshGeometry3D> ExtractMeshes(
            IEnumerable<GeometryModel3D> models)
        {
            var result = new List<MeshGeometry3D>();
            foreach (var gm in models)
            {
                if (gm.Geometry is MeshGeometry3D mesh && mesh.Positions.Count > 0)
                    result.Add(mesh);
            }
            return result;
        }

        // ── Helpers: material naming ─────────────────────────────────────────

        private static void CollectDielectrics(PcbStackup stackup,
            Dictionary<string, (double Eps, double Kappa)> mats)
        {
            foreach (var layer in stackup.Layers)
            {
                if (layer.IsConductive) continue;
                string varName = MaterialVarName(layer);
                if (!mats.ContainsKey(varName))
                {
                    double kappa = layer.Material switch
                    {
                        LayerMaterial.FR4         => 0.02,
                        LayerMaterial.Rogers4350B => 0.004,
                        LayerMaterial.Rogers4003C => 0.003,
                        LayerMaterial.PolyimidePI => 0.01,
                        LayerMaterial.Rogers5880  => 0.001,
                        LayerMaterial.AluminumCCL => 0.02,
                        LayerMaterial.SolderMask  => 0.02,
                        LayerMaterial.Air         => 0,
                        _                        => 0.02,
                    };
                    mats[varName] = (layer.DielectricConstant, kappa);
                }
            }
        }

        /// <summary>
        /// Returns true when a conductive layer has actual copper content that should
        /// be exported (Gerber data, manual shapes, or antenna traces).
        /// Layers with only the default pour (used for 3-D visualisation) return false.
        /// </summary>
        private static bool CopperLayerHasContent(
            Layer layer, MainViewModel vm, bool isCarrier)
        {
            if (!layer.IsConductive) return false;
            if (layer.HasGerber) return true;
            // Any manual shape / antenna on this layer?
            return vm.ManualShapes.Any(s =>
                s.IsCarrier == isCarrier &&
                s.LayerName == layer.Name &&
                s.ShowIn3D);
        }

        /// <summary>Collect unique X and Y coordinates from polygon vertices for mesh seeding.</summary>
        private static void CollectPolyEdges(
            IEnumerable<ShapeVertex> verts, SortedSet<double> xs, SortedSet<double> ys)
        {
            foreach (var v in verts)
            {
                xs.Add(Math.Round(v.X, 6));
                ys.Add(Math.Round(v.Y, 6));
            }
        }

        /// <summary>
        /// Insert midpoints between adjacent seed lines whose gap is large compared
        /// to the smallest feature.  This ensures the FDTD mesh resolves inter-trace
        /// coupling in structures such as meander antennas.  Gaps wider than 3× the
        /// median small-gap are bisected so every sub-gap ≤ that limit.
        /// Only operates inside the bounding box of the original seeds (ignoring
        /// board-outline lines far from the antenna geometry).
        /// </summary>
        private static void AddMidpointRefinement(SortedSet<double> lines, double minStep = 0.05)
        {
            if (lines.Count < 3) return;

            var sorted = lines.ToList();

            // Collect all gaps
            var gaps = new List<double>();
            for (int i = 0; i < sorted.Count - 1; i++)
            {
                double g = sorted[i + 1] - sorted[i];
                if (g > 1e-6) gaps.Add(g);
            }
            if (gaps.Count < 2) return;

            gaps.Sort();
            // Use a percentile-based threshold: take the median of the lower half
            // of gaps (i.e. the 25th percentile) as the representative small feature.
            int q1Idx = Math.Max(0, gaps.Count / 4);
            double refGap = gaps[q1Idx];

            // Threshold: subdivide gaps larger than 2× the reference small gap,
            // but never below 0.15 mm to avoid generating excessive mesh lines.
            double threshold = Math.Max(refGap * 2, 0.15);
            // Also ensure subdivisions never produce cells smaller than minStep.
            if (threshold < minStep) threshold = minStep;

            // Only refine inside the "dense" region — find the bounding box of
            // seeds that are NOT the two extremes (board outline corners).
            // We skip the single largest gap on each side to avoid refining
            // the air padding between the board edge and the geometry.
            double innerMin = sorted.Count > 2 ? sorted[1] : sorted[0];
            double innerMax = sorted.Count > 2 ? sorted[sorted.Count - 2] : sorted[sorted.Count - 1];

            var toAdd = new List<double>();
            for (int i = 0; i < sorted.Count - 1; i++)
            {
                double a = sorted[i], b = sorted[i + 1];
                // Only refine within the inner range
                if (b <= innerMin || a >= innerMax) continue;
                double gap = b - a;
                if (gap > threshold + 1e-9)
                {
                    int n = (int)Math.Ceiling(gap / threshold);
                    if (n > 10) n = 10;
                    double step = gap / n;
                    // Reduce subdivisions until each cell >= minStep
                    while (n > 1 && step < minStep - 1e-9) { n--; step = gap / n; }
                    if (n <= 1) continue;
                    for (int j = 1; j < n; j++)
                        toAdd.Add(Math.Round(a + j * step, 6));
                }
            }
            foreach (var v in toAdd)
                lines.Add(v);
        }

        /// <summary>
        /// Ensure every gap narrower than <paramref name="maxRes"/> (i.e. gaps that
        /// represent trace widths rather than open-space regions) contains at least
        /// <paramref name="minCells"/> mesh intervals.  Gaps that already have enough
        /// intervals or that are wider than the normal mesh resolution are skipped.
        /// </summary>
        private static void SubdivideNarrowGaps(SortedSet<double> lines, int minCells, double maxRes, double minCellSize = 0.05)
        {
            if (lines.Count < 2 || minCells < 2) return;

            var sorted = lines.ToList();
            var toAdd = new List<double>();

            for (int i = 0; i < sorted.Count - 1; i++)
            {
                double a = sorted[i], b = sorted[i + 1];
                double gap = b - a;
                if (gap < 1e-6) continue;
                // Only refine gaps narrower than the normal mesh cell size — these
                // correspond to trace widths that would otherwise get ≤ 1 cell.
                if (gap >= maxRes) continue;
                // Compute how many cells we can fit while keeping each >= minCellSize.
                int n = minCells;
                while (n > 1 && gap / n < minCellSize - 1e-9) n--;
                if (n <= 1) continue;   // gap is already small enough

                double step = gap / n;
                for (int j = 1; j < n; j++)
                    toAdd.Add(Math.Round(a + j * step, 6));
            }

            foreach (var v in toAdd)
                lines.Add(v);
        }

        /// <summary>
        /// Remove intermediate lines that are closer than <paramref name="minStep"/>
        /// to their neighbour.  Original polygon-edge lines (which existed before
        /// refinement/subdivision) are never removed — only the inserted midpoints.
        /// Guarantees every gap in the final set &gt;= minStep.
        /// </summary>
        private static void EnforceMinStep(SortedSet<double> lines, double minStep)
        {
            if (lines.Count < 3 || minStep <= 0) return;
            var sorted = lines.ToList();
            var toRemove = new List<double>();
            for (int i = 1; i < sorted.Count - 1; i++)
            {
                if (sorted[i] - sorted[i - 1] < minStep - 1e-9)
                    toRemove.Add(sorted[i]);
            }
            foreach (var v in toRemove)
                lines.Remove(v);
        }


        /// <summary>Generate a valid Python variable name for a dielectric material.</summary>
        private static string MaterialVarName(Layer layer)
        {
            string name = layer.Material switch
            {
                LayerMaterial.FR4         => "fr4",
                LayerMaterial.Rogers4350B => "rogers4350b",
                LayerMaterial.Rogers4003C => "rogers4003c",
                LayerMaterial.PolyimidePI => "polyimide",
                LayerMaterial.Rogers5880  => "rogers5880",
                LayerMaterial.AluminumCCL => "aluminum_ccl",
                LayerMaterial.SolderMask  => "soldermask",
                LayerMaterial.Air         => "air",
                _                         => $"dielectric_eps{layer.DielectricConstant:F1}".Replace('.', '_'),
            };
            return $"mat_{name}";
        }

        // ── Helpers: coordinate system ───────────────────────────────────────

        /// <summary>
        /// Z coordinate of the TOP face of <paramref name="target"/> in the stackup.
        /// Same logic as MainWindow.ComputeLayerZFace.
        /// When <paramref name="usePecSheets"/> is true, conductive layer thickness
        /// is treated as zero so the copper plane sits at the interface.
        /// </summary>
        private static double ComputeLayerZFace(
            IEnumerable<Layer> layers, Layer target, bool isCarrier = true,
            bool usePecSheets = false)
        {
            if (isCarrier)
            {
                double z = 0.0;
                foreach (var l in layers)
                {
                    if (l == target) return z;
                    double t = (usePecSheets && l.IsConductive) ? 0 : l.Thickness;
                    z -= t;
                }
            }
            else
            {
                double zBase = MountGap;
                foreach (var l in layers.Reverse())
                {
                    double t = (usePecSheets && l.IsConductive) ? 0 : l.Thickness;
                    double top = zBase + t;
                    if (l == target) return top;
                    zBase = top;
                }
            }
            return 0.0;
        }
    }
}
